### PR TITLE
added key event for login-signup

### PR DESCRIPTION
**Pull request by Asymtode712**
## Description

- Added the key event for Logn-Signup, now an user will be able to submit the form with keeping any field active

@mdazfar2 Please review and merge this PR

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Asymtode712 Actually, this has already been implemented. I thought you were not interested since you did not reply, so Ayushmaan completed it.

**Comment by Asymtode712** [comment]
@mdazfar2 Sorry for responding late,

Actually the current key behaviour only works when we have an active field......Like if we are on the password or email field and we click on Enter key then only it works and not when we are not on any active field.....so can check it on our deployed site....I tried it and so I added an useEffect for overall component so that we won't require to be on an active field.......

Please check once.....

**Comment by mdazfar2** [comment]
@Asymtode712, I'm a bit confused.  Would it be possible to share a demo video or provide more details to help me understand what you're referring to?

**Comment by Asymtode712** [comment]
@mdazfar2 


https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/905e1c2f-7fa1-4fdd-9f7e-8d47f5051c63

**Comment by Asymtode712** [comment]
@mdazfar2 The thing is I have previously applied this to all the components in the given way only so that we won't have to keep an active field and the key event can still perform its functioning.....so this was the component which was lagging this effect

**Comment by mdazfar2** [comment]
@Asymtode712,
Ah, I see now! Thank you so much for taking the time to explain that. It clarifies things a lot.  While no other contributor included a video demonstration, yours was very helpful.  It really sets you apart!

- Could you please raise an issue on that?

**Comment by Asymtode712** [comment]
@Asymtode712 Actually I don't need any points on that as this was to be done by me in the previous issue ( #737 ) only.....So please just merge it no need to label it

Also, thanks for the appreciation😇🙏

**Comment by Asymtode712** [comment]
@mdazfar2 You can reopen and merge this PR🙏

**Comment by mdazfar2** [comment]
> @mdazfar2 You can reopen and merge this PR

@Asymtode712 Oh! ok I thought you would create a new PR.

**Pull request merged**
