### PR TITLE
Fix Cards Scoial icons hover overlap

### LINKED ISSUE #711: BUG: In team main 4 cards social icons hover effects overlapping
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

image

**I will give it proper margin from left and right and make it perfect.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by zalabhavy**
Fixes #711

I have give proper margin right and left also add some style.

Basically i have give box shadow to social link so that part looks like one separate div and when you hover on that you can feel hover effects on that div also with some scale and shadow effect.

If you don't want I will remove it.

image

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Please check my PR ?

**Comment by mdazfar2** [comment]
hey @zalabhavy the hover effect should not be cover all as shown in the below screenshot try to do like that in every icons of every founder and maintainer card

<br>

image

**Comment by zalabhavy** [comment]
@mdazfar2  changes done !

image

image

**Comment by mdazfar2** [comment]
Hey @zalabhavy, sorry for the late reply! Remove the div and in the current website, try to adjust that hover. Don't add any div with extra shadow and all.

image

<br>

### Try to do adjust only this card of hover

<br>

image

**Comment by zalabhavy** [comment]
@mdazfar2 Done !

image

**Comment by mdazfar2** [comment]
@zalabhavy you exceed the gap from right and left which looks strange than current deployed website

<br>

image

**Comment by zalabhavy** [comment]
@mdazfar2 Please check new PR #719

**Pull request closed without merging**
