### PR TITLE
 CI/CD Pipeline using AWS

### PR DESCRIPTION
**Pull request by revanth1718**
Resolves Issue #39 
Project: complete CI/CD pipeline using CodeBuild, CodeDeploy, and CodePipeline.

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
Great work @revanth1718 ig you are Pro DevOps Practitioner ;)

- Rename folder name to --> CI/CD Pipeline using AWS

**Comment by revanth1718** [comment]
can you label this project as level 3 because this content worth it

**Comment by mdazfar2** [comment]
> Thank you , i am a Beginner in Devops. can you label this project as level 3 because this content worth it .

@sanjay-kv Can I give this level 3 label as it has added very important topic?

**Comment by revanth1718** [comment]
I cant change the name to --> CI/CD Pipeline using AWS. Because new folder is creating so could you change the name or keep it like this.

**Comment by mdazfar2** [comment]
> I cant change the name to --> CI/CD Pipeline using AWS. Because new folder is creating so could you change the name or keep it like this.

<br>
No problem, I will change it myself

**Pull request merged**
