### PR TITLE
Fixed list of menu items is not visible in dark mode and added hover of menu items in both mode when size of screen is reduced .

### LINKED ISSUE #479: BUG: list of menu items is not visible in dark mode , hover of menu items in both mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

menu items is not visible in dark mode in all pages 

issue :
Screenshot 2024-06-17 171229

solved:

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/0ba0409c-760e-4909-b891-7ed4515a897c

added hover on list of menu items as per the theme 
 before : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/447d9653-a17a-4574-a7d4-8a48316d8ced

solved :

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/03f21abc-edb0-4769-810b-5bd8f60c6e52

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixed #479 
1. The menu items now visible in dark mode .
### BEFORE

Screenshot 2024-06-17 171229

### AFTER
https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/0484f51d-cbba-4db3-97df-bd150125e76b

2. Added hovering effect to the menu items in all pages according to theme of the project when size of screen is reduced .

### BEFORE

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/c09ac164-9363-4ac7-9c84-a63485c9d1ab

### AFTER

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/b910a744-04c5-43ad-8cbe-f5565c505f73

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
Great work @ANKeshri 

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Comment by mdazfar2** [comment]
@ANKeshri You didn't sync your fork with the update, and after merging your pull request, it is deleting a section from my landing page. I didn't take care of it.

**Comment by ANKeshri** [comment]
> @ANKeshri You didn't sync your fork with the update, and after merging your pull request, it is deleting a section from my landing page. I didn't take care of it.

@mdazfar2 sorry sir from next time i will take care of it . Sir can you please tell me the section which was deleted I will try to fix it .

**Comment by mdazfar2** [comment]
No problem! Let us take it

**Comment by mdazfar2** [comment]
No problem! Let us take it

**Comment by ANKeshri** [comment]
> No problem! Let us take it

thank you sir

**Comment by ANKeshri** [comment]
@mdazfar2 sir please give this pr "gssoc" label so that it can get included in my gssoc

**Comment by mdazfar2** [comment]
Added

**Comment by ANKeshri** [comment]
> Added

thanks

**Pull request merged**
