### PR TITLE
add hovering effect on menu bar items when screen size is reduced .

### LINKED ISSUE #664: Feat: adding similar hovering effect on items of drop down list as it is in nav bar items
### Describe the feature

i will be adding hovering effect on buttons of drop down list just as the hovering effect present in nav bar items .

### Add ScreenShots

as we hover there is nothing happening .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9fcabfbb-4d6c-46b1-93d6-d6cc201e87ae

i wil add hovering effect like shown below .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/0a94b50d-3649-4b4b-afac-ce2319462800

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #664 

- before there was no hovering effect on items of menu bar when screen size was reduced as shown in the video .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/030b40a6-62f9-4066-9b90-e3c90bb618ea

- now i have added the hovering effect to all the items in menu bar as per the theme as you can see in the video . 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/56d29b69-e455-4b1c-aab4-41e744f0793b

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 please review it

**Comment by mdazfar2** [comment]
@ANKeshri I see that you forgot to add comments again. Next time, please keep in mind to update comments with every change.

**Comment by ANKeshri** [comment]
> @ANKeshri I see that you forgot to add comments again. Next time, please keep in mind to update comments with every change. This time I'll merge only for you.

@mdazfar2 sorry I am unable to understand should I add comment in the code or should I commit every changes I do .

**Comment by mdazfar2** [comment]
@ANKeshri 
I am talking about adding comments in the code if you change something and trying to give a good message when you commit.

**Comment by ANKeshri** [comment]
> @ANKeshri I am talking about adding comments in the code if you change something and trying to give a good message when you commit.

@mdazfar2 sure I will keep in mind .

**Pull request merged**
