### PR TITLE
Backend added for feedback form and styles fixed

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
image
image
image

issue #170 solved

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 check the PR

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal It has gotten much better than before.


## I am getting this error, how do I get the result?

image

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 you run the server?

1st go to the Official-website folder in the terminal
2nd type `npm install`
3rd type `node index.js`

**Comment by RamakrushnaBiswal** [comment]
hy @mdazfar2 is there any discord channel where we can communicate

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal Check Discord, I texted you.

**Review by mdazfar2 — APPROVED** [review]

**Pull request merged**
