### PR TITLE
Dark mode

### LINKED ISSUE #175: Dark Mode Issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Apurv7777**
Fixes #175 

### Fully functional dark mode is applied. Please give level accordingly. 😊

### CODE REVIEW

**Comment by mdazfar2** [comment]
## @Apurv7777 It is not full dark mode on sides of Feedback

<br>

image

<br>

## My expectation is-
<br>

image

<br>

- **@Apurv7777  can you integrate these all in only one page. Means when the user click dark mode it is enable all the pages. I will give lavel3 label for this.**

**Comment by Apurv7777** [comment]
I have an suggestion , if we make the color of button to gray, it seems like it is **disabled**. So, I suggest to not change the color of button.

**Comment by mdazfar2** [comment]
@Apurv7777 It is merged by other issue could you please work on new issue; when the user clicks "dark mode icon" on "Homepage" it is enable all the pages. Means all of the pages will automatically dark.

**Comment by Apurv7777** [comment]
> @Apurv7777 It is merged by other issue could you please work on new issue; when the user clicks "dark mode icon" on "Homepage" it is enable all the pages. Means all of the pages will automatically dark.

It is done already in this PR.

**Comment by mdazfar2** [comment]
> > @Apurv7777 It is merged by other issue could you please work on new issue; when the user clicks "dark mode icon" on "Homepage" it is enable all the pages. Means all of the pages will automatically dark.
> 
> It is done already in this PR.

Checkout the deployed link and use dark mode and see it enables on feedback section or not. Let me know fast

**Comment by Apurv7777** [comment]
> > > @Apurv7777 It is merged by other issue could you please work on new issue; when the user clicks "dark mode icon" on "Homepage" it is enable all the pages. Means all of the pages will automatically dark.
> > 
> > 
> > It is done already in this PR.
> 
> Checkout the deployed link and use dark mode and see it enables on feedback section or not. Let me know fast

I recommend you to merge this PR only for dark mode , because my implementation is simpler than the last dark mode fix and do think about this suggestion https://github.com/mdazfar2/HelpOps-Hub/pull/215#issuecomment-2151383010

**Comment by Apurv7777** [comment]
And feedback page in my PR is also good enough ,  I think no changes are needed.

**Comment by Apurv7777** [comment]
### Now, all your requested changes , along with my suggestion all resolved.

**Comment by Apurv7777** [comment]
### Now, all your requested changes , along with my suggestion are resolved. @mdazfar2

**Comment by mdazfar2** [comment]
What is this @Apurv7777 😶

<br>

image

**Comment by Apurv7777** [comment]
### I will remove that icon.

**Comment by Apurv7777** [comment]
image

### It is perfect in my localhost.

**Pull request closed without merging**
