### PR TITLE
Feat/hover effect cards on the section we are creative .

### LINKED ISSUE #501: Feat:Add Hover effects on We are creative section's cards.
### Describe the feature

I want to add hover effects like scale , shadow ect.
I will give better looks

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixed #501 

added the hovering effect on the cards of we are creative section .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/c2b84a63-5338-4e68-a7c5-1ffe8dc25532

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 please review this pr and if want any changes let me know .

**Comment by mdazfar2** [comment]
@ANKeshri Sorry I was a little busy, if you had ping me up on [Discord](https://discord.gg/UWTrRhqywt) server I would have known.

**Comment by mdazfar2** [comment]
@ANKeshri when we are moving the cursor on the card the cursor is change into text cursor please change into as usual normal cursor

**Comment by ANKeshri** [comment]
> @ANKeshri when we are moving the cursor on the card the cursor is change into text cursor please change into as usual normal cursor

solving it

**Comment by ANKeshri** [comment]
@mdazfar2 done

**Comment by mdazfar2** [comment]
@ANKeshri Great, I will review it by morning.

**Review by mdazfar2 — APPROVED** [review]
lgtm

**Pull request merged**
