### PR TITLE
[Feature] : Implement the proper UI

### PR DESCRIPTION
**Pull request by sivaprasath2004**
Hello @mdazfar2 ,
- In this project Now  I can change the proper Ui.

### Before

[Screencast from 2024-06-05 21-01-35.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/2237d821-7aec-4bb7-8bc9-050ad18c3157)

### After

[Screencast from 2024-06-06 11-51-00.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/baa73942-50a6-4996-b9c1-d6e4b4b2695e)

### CODE REVIEW

**Review by mdazfar2 — COMMENTED** [review]
@sivaprasath2004 I can't understand difference between after and before

**Comment by sivaprasath2004** [comment]
Hello @mdazfar2 ,
- In this project main problem in the css
```
.dark-mode #folders-container {
  background-color: #333;
  /* Dark background color */
  color: #fff;
  /* Light text color */
}

.dark-mode .folder-card {
  background-color: #1a1a1a;
  /* Dark card background */
  color: #fff;
  /* Light text color */
  border-color: #555;
  /* Darker border color */
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
  /* Darker box shadow */
}

.dark-mode .folder-card:hover {
  background-color: #333;
  /* Dark hover background */
  box-shadow: 5px 5px 20px #00ccff;
  /* Example hover effect in dark mode */
  transform: scale(1.1);
  border-radius: 1.5rem;
}

/* Example: Dark mode heading for folder name */
.dark-mode .folder-card h3 {
  color: #fff;
  /* Light heading color */
}
```
- This is collapse for the searching so i will use easy to change 
```
.dark-mode #folders-container {
 filter: invert(1);
} 
.dark-mode .folder-card {
color: black;
box-shadow: 0 2px 6px rgb(255, 255, 255);
}
```
- this is perfect changing not collapse in the project..

**Comment by sivaprasath2004** [comment]
Before In the `Dark mode` to search `U` then the `.folder-card` can be change `lightmode color` of the white color.
- so i will changed it...

**Comment by mdazfar2** [comment]
### @sivaprasath2004 In my case everything is well, try to find another issue, there are so many glitches on my web find and raise

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/9efbe34c-8265-46c4-adec-625fabfdfdb8

<br>

- & @sivaprasath2004  please don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Pull request closed without merging**
