### PR TITLE
fixed Text overflow in mobile view in qna section #1372

### LINKED ISSUE #1372: Text overflow in mobile view in qna section
### Description

Please assign me this issue under gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

### Screenshots

IMG_7534

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by ShivanshPlays**
closes #1372

Earlier: 

https://github.com/user-attachments/assets/d1bee7c7-0f0c-4505-8718-d411361bde61

Now:

https://github.com/user-attachments/assets/995e320e-8d28-4bd7-afc0-99de6e6fa98a

### CODE REVIEW

**Comment by ShivanshPlays** [comment]
> section


As you can see in the second video, user can scroll from left to right in order to read the content

**Comment by mdazfar2** [comment]
@ShivanshPlays This will be a bit hard for the user, hope you understand!

**Comment by ShivanshPlays** [comment]
Okay, so do you want me to remove the scroll and just keep the content as is available for sliding and seeing?

**Comment by mdazfar2** [comment]
@ShivanshPlays exactly 💯

**Comment by ShivanshPlays** [comment]
Now it is like this: 
image

**Comment by mdazfar2** [comment]
@ShivanshPlays Yes, that's nice, but send me the screen recording of the desktop view and mobile responsiveness as well, just to confirm that it looks the same on both.

**Comment by ShivanshPlays** [comment]
https://github.com/user-attachments/assets/9db31e07-7a76-4d70-befe-70f6fdd0ff5c

**Review by mdazfar2 — APPROVED** [review]
Thank you @ShivanshPlays

**Pull request merged**
