### PR TITLE
Added smooth hover scale

### LINKED ISSUE #1095: Feat:Add some scale on get-started and start now button
### Describe the feature

image

image

I will add some scale so user can feel button.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by zalabhavy**
Fixes #1095

Added Smooth scale effect on buttons.

https://www.loom.com/share/55c4af1484c04ad794f730d7fc8d3f18

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Please check it and merge !

Thank You !

**Comment by mdazfar2** [comment]
@zalabhavy can you add hover like that if possible please update this type of hover.

<br>


https://github.com/user-attachments/assets/455c4ae2-5624-43ac-b082-532e70e8ee6c

**Comment by zalabhavy** [comment]
@mdazfar2 Done !
https://www.loom.com/share/8b88beed8dc647de82e9f29782a3d239

**Review by mdazfar2 — APPROVED** [review]
lgtm ✨

**Pull request merged**
