### PR TITLE
To organize content of the organizing page (Issue #114)

### PR DESCRIPTION
**Pull request by ananyag309**
Updated the description of content page and

Update contributor.js

made enhance the readability, maintainability, and efficiency of your code.
1) In the old code, you directly appended HTML strings to create contributor cards. In the new code, I have dynamically created HTML elements and manipulated them, which is a cleaner approach and makes the code more maintainable.
2) created img, a, and span elements dynamically and set their attributes accordingly.
3) In the old code, there was a variable var cheak = 0; which seems unused and has been removed in the new code.
4) corrected a typo in the p tag where it says "Open-sourec contributor" to "Open-source contributor".
5) made minor adjustments to the structure and styling of the contributor cards, such as removing commented-out HTML and fixing indentation.

and a few more changes.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@ananyag309 could you please share the screenshot

**Comment by ananyag309** [comment]
@mdazfar2 sir sorry to disturb again, but please add gssoc and level tag too. so that when merged my points can get reflected.

thank you

**Comment by mdazfar2** [comment]
> @mdazfar2 sir sorry to disturb again, but please add gssoc and level tag too. so that when merged my points can get reflected.
> 
> thank you

- That's all fine. Share the screenshot of what you have changed ?

**Comment by ananyag309** [comment]
@mdazfar2 
earlier :
earlier 1

earlier 2


updated:

now 1


now 2

**Pull request closed without merging**
