### PR TITLE
Implement User-Friendly Feedback Section

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
Issue #81 

This pull request implements a user-friendly feedback section at the bottom of the HelpOps-Hub page, addressing issue #81. The feedback section includes the following features:

A concise prompt encouraging users to leave feedback.
Input fields for optional name and email, allowing users to provide contact information if desired.
A textarea for users to input their feedback.
A submit button to send the feedback.

This feedback section aims to gather valuable insights and suggestions from users, facilitating continuous improvement of the website. The design is integrated seamlessly with the existing page layout, ensuring a cohesive user experience. Screenshots of the implemented feedback section will be provided in the pull request for reference.

https://github.com/mdazfar2/HelpOps-Hub/assets/109781385/34b55c29-5948-44fc-b80c-887fcc49cd67

### CODE REVIEW

**Comment by mdazfar2** [comment]
@thevijayshankersharma It is good

- But I will share the Figma design with you! Then update your work accordingly.

**Comment by thevijayshankersharma** [comment]
@mdazfar2 when will you send it ?

**Comment by mdazfar2** [comment]
@thevijayshankersharma Around 11:00 PM.

**Comment by mdazfar2** [comment]
Hi @thevijayshankersharma The form you have made is also good but it is very big in size. You must have to short the size.
<br/>
image
<br>

- How would you feel if something like this was made?

**Comment by thevijayshankersharma** [comment]
Is that my feedback form which you have sent ??

**Comment by thevijayshankersharma** [comment]
Is that my feedback form which you have sent ?
@mdazfar2 Do you have discord server to talk.

**Comment by mdazfar2** [comment]
> Is that my feedback form which you have sent ??

Nope! I have just design it that you you'll have to make the rectangle a little smaller like the above ss.

**Comment by thevijayshankersharma** [comment]
Sure I will make it by tomorrow.

**Comment by thevijayshankersharma** [comment]
@mdazfar2 Done 

image

**Review by mdazfar2 — APPROVED** [review]
Great work but you can create more user friendly please be working on. Right now I'm merging it for you.

- could you please work on another issue creating full responsive on mobile if you want to work on it please raise an issue i will give you the GSSOC level3 label.

**Comment by thevijayshankersharma** [comment]
@mdazfar2 I think it's already responsive tell me specifically what should I do I will do it.

**Comment by mdazfar2** [comment]
@thevijayshankersharma 

<br>

image

- **Look at once here**

**Comment by thevijayshankersharma** [comment]
@mdazfar2 you mean the header section ? I will give it a try.

**Comment by mdazfar2** [comment]
> @mdazfar2 you mean the header section ? I will give it a try.

<br>

Header section as well as the repository card which is not on systematically.

**Pull request merged**
