### PR TITLE
Feat:Want to change color theme in dark mode #551

### PR DESCRIPTION
**Pull request by nishant0708**
issue: #551 

Screenshot 2024-06-22 142819
Screenshot 2024-06-22 142830
Screenshot 2024-06-22 142855
Screenshot 2024-06-22 142912

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @mdazfar2 please review  this pr and let me know the changes

**Comment by mdazfar2** [comment]
@nishant0708 please mention your issue

**Comment by nishant0708** [comment]
> @nishant0708 please mention your issue

#551

**Comment by mdazfar2** [comment]
@nishant0708, can you also implement dark mode on reload as well? Currently, when I switch to dark mode, it reverts to light mode on page reload.

**Comment by nishant0708** [comment]
> @nishant0708, can you also implement dark mode on reload as well? Currently, when I switch to dark mode, it reverts to light mode on page reload.

Arey you talking about skeletons and wrappers right??

**Comment by mdazfar2** [comment]
> Arey you talking about skeletons and wrappers right??

<br>

**No! @nishant0708 I am talking about this reload page** 👇

<br>

image

**Comment by nishant0708** [comment]
> > Arey you talking about skeletons and wrappers right??
> 
> 
> **No! @nishant0708 I am talking about this reload page** 👇
> 
> 
> image

okay doing it

**Comment by nishant0708** [comment]
hey @mdazfar2  please check it now

https://github.com/mdazfar2/HelpOps-Hub/assets/101548649/dd032d4f-fcce-4139-bef6-99d269638192

**Comment by mdazfar2** [comment]
@nishant0708 Why did you update to the `Benjamin` folder? Please remove changes from the `Benjamin` folder

**Comment by nishant0708** [comment]
> @nishant0708 Why did you update to the `Benjamin` folder? Please remove changes from the `Benjamin` folder

i was trying to change color from there  but undo most of the changes . let me paste old file wait a sec

**Comment by mdazfar2** [comment]
@nishant0708 You can contribute to the `Benjamin` folder once it is deployed

**Comment by nishant0708** [comment]
hey @mdazfar2  done

**Comment by nishant0708** [comment]
> @nishant0708 You can contribute to the `Benjamin` folder once it is deployed

oo got it i don't knew that i was just looking for some class as multiple folder was have same class so i reached there somehow sorry for the trouble

**Review by mdazfar2 — APPROVED** [review]
looks good to me

**Pull request merged**
