### PR TITLE
Resonsive Blog post

### PR DESCRIPTION
**Pull request by mukilan2815**
Issue: #958 

Screenshots

image_2024-07-14_113242919
Screenshot from 2024-07-14 11-29-43

Please close this PR under GSSOC'24 Level 3

### CODE REVIEW

**Comment by mdazfar2** [comment]
@mukilan2815 Adjust this gap like this in desktop view and then make it responsive again

<br>

image

<br>

- **You can take reference from this website I am attaching the link here** - [Dev.to website Desktop and responsive as well](https://dev.to/anmolbaranwal/shortcut-to-find-open-source-projects-100x-faster-3lje)

**Comment by mukilan2815** [comment]
need to remove that space in mobile layout ah?

**Comment by mdazfar2** [comment]
@mukilan2815 did you complete this as well desktop?

**Comment by mukilan2815** [comment]
Completed everything bro u can merge now

**Comment by mdazfar2** [comment]
@mukilan2815 just for confirm did you update sync fork?

**Comment by mdazfar2** [comment]
@mukilan2815 You are very delayed in replying. I am responding to all of your messages quickly, but by the way, I noticed that you did not make any changes to the desktop view as I mentioned earlier.

<br>

image

**Comment by mukilan2815** [comment]
can u please explain me again. what are the things i need to do? I have made it responsive for mobile and i didnt make anything change in desktop view

**Comment by mdazfar2** [comment]
> can u please explain me again. what are the things i need to do? I have made it responsive for mobile and i didnt make anything change in desktop view. I am replying the message once i see it sorry for the delay bro..

Okay no problem @mukilan2815  do one last thing update sync fork and please resolve your conflict as well

**Comment by mukilan2815** [comment]
Done everything

**Comment by mdazfar2** [comment]
@mukilan2815 See here are the below changes which you made:

## This is your deployment changes 👇
image

## And the current deployment website 👇
image

***Hope you understand the changes is made problem with desktop view please resolve this we need it as soon as possible***

**Comment by mukilan2815** [comment]
In mine the size  reduces right?

**Comment by mdazfar2** [comment]
@mukilan2815 Look at the video below; I will provide voice instructions as well.

<br>


https://github.com/user-attachments/assets/76a5343a-f564-43a7-a6d8-bb08471bbe8f

**Comment by mukilan2815** [comment]
Ok bro i got it i will update soon

**Comment by mukilan2815** [comment]
Check it now bro

**Comment by mukilan2815** [comment]
check it now bro

**Comment by mdazfar2** [comment]
@mukilan2815 I apologize, but I need to close this pull request for now. Please don't be discouraged!

**Pull request closed without merging**
