### PR TITLE
Fix : Added Button in Mode change like Sponsor also make sponsor button attractive

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #647 

I have style sponsor button give new look to it.
Make mode change svg under one button like sponsor.
Now navbar looks good.

https://www.loom.com/share/697338d2e85a4c07ab6d4fe1fe479223

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Please check it i have updated fork then made changes that you have told !

**Comment by mdazfar2** [comment]
I see that you have not updated your forked branch yet because it is not updated on my deployment server, unlike the version available on the deployed server. @zalabhavy

**Comment by zalabhavy** [comment]
@mdazfar2 Now check it !

**Comment by zalabhavy** [comment]
@mdazfar2 you can check new PR in this i think last PR that you merge show changes of that.
New PR #670

**Pull request closed without merging**
