### PR TITLE
Scroll to top button added

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #92 
Here I added Scroll to Top Button with same color as navbar.
image
Working Video of that
https://www.loom.com/share/2653c4306c064a9689ca3d6d407f85ed

### CODE REVIEW

**Comment by zalabhavy** [comment]
hey @mdazfar2 can you please check it and merge. Can you provide this to **level3** ?

**Review by mdazfar2 — APPROVED** [review]
Thank You @zalabhavy

**Comment by mdazfar2** [comment]
**Hi @zalabhavy the `Scroll to Top Button` is not showing what did you do?**

<br>

image

**Comment by mdazfar2** [comment]
> @mdazfar2 it's ok. Thank You !! I will create new issues in this repo. Really u are a best and active PA I had seen in Gssoc'24.

<br>

Sure @zalabhavy Create new issue which really need on our web.

**Pull request merged**
