### PR TITLE
About Page Images styled video added

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #266

I added 3d effects on images.
I made About page's image Styled with adding effect like Shadow , hover and transitions.
Align all sentence in one align as shown in screenshot.
Added a youtube official video.

https://www.loom.com/share/a6d599c6dbba424dbd8ddebbf0a7c7cd

### CODE REVIEW

**Comment by mdazfar2** [comment]
@zalabhavy keep the end points of all sentences the same

**Comment by zalabhavy** [comment]
@mdazfar2 I make better than previous alignment of sentences but if i do what you have say spellings get cuts and that not looks good.

**Comment by zalabhavy** [comment]
@mdazfar2 I did what i can do. I give my best and also it takes 2 hours to me for make effects and add video and alignment of sentence.
I hope you can understand.
**Thank You !!**

**Comment by mdazfar2** [comment]
@zalabhavy I don't have any problem with your pr but your pr is not on deploying variable that's why i can not merge. Could you please update your sync and then try to create pr again

**Comment by zalabhavy** [comment]
@mdazfar2 Ok I will do that

**Pull request closed without merging**
