### PR TITLE
made the navbar attach to top and fixed feedback form

### PR DESCRIPTION
**Pull request by Stiffpixels**
# All the features added and bugs fixed:
1. Made the navbar stick to the top when scrolling down for easy navigation on.
2. Made the navbar responsive for mobile and tablet.

https://github.com/mdazfar2/HelpOps-Hub/assets/32983571/aed00157-c536-4253-ab39-d7c5c1894060

3. Made the feedback form responsive on mobile.

image

Fixes issue #181

### CODE REVIEW

**Comment by mdazfar2** [comment]
## @Stiffpixels You made the search icon really thin.

image


## Here is the below our current search icon looks like-
<br>

image

- Currenly search icon looks like attractive in case of you which you created pr.

**Comment by Stiffpixels** [comment]
> ## @Stiffpixels You made the search icon really thin.
> 
> image
> 
> 
> ## Here is the below our current search icon looks like-
> <br>
> 
> image
> 
> - Currenly search icon looks like attractive in case of you which you created pr.

Okay I will make the change

**Comment by Stiffpixels** [comment]
> ## @Stiffpixels You made the search icon really thin.
> 
> image
> ## Here is the below our current search icon looks like-
> 
> image
> 
>     * Currenly search icon looks like attractive in case of you which you created pr.

Done! also fixed the searchbar on tablet 
current:
image

fixed:
image

**Comment by mdazfar2** [comment]
@Stiffpixels please resolve conflict

**Comment by Stiffpixels** [comment]
@mdazfar2 resolved all the conflicts

**Comment by Stiffpixels** [comment]
@mdazfar2 please merge before more conflicts arise.

https://github.com/mdazfar2/HelpOps-Hub/assets/32983571/77c22a8a-abec-4acb-ad52-e35f5ea9de10

**Pull request closed without merging**
