### PR TITLE
Fixed hover effect on resource details page and route name

### PR DESCRIPTION
**Pull request by vansh-codes**
Issue no #658 

**Earlier**
image
image

**NOW**
image
image

Fixed the hover effect and route name from "abouts" to "about"

### CODE REVIEW

**Comment by mdazfar2** [comment]
@vansh-codes update sync fork

**Comment by vansh-codes** [comment]
@mdazfar2 Synced. Please check now and merge. Thank You!

**Comment by mdazfar2** [comment]
@vansh-codes please update sync fork

- current i am merge someone other PR

**Comment by vansh-codes** [comment]
> @vansh-codes please update sync fork
> 
> * current i am merge someone other PR

@mdazfar2 Synced ✅

**Review by mdazfar2 — COMMENTED** [review]
Thanks! @vansh-codes

**Pull request merged**
