### PR TITLE
Added Color as before 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added the color as before on the website header page .

closes : #517 

Screenshot 2024-06-19 231522

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]

**Comment by sanjay-kv** [comment]
image

@Ayushmaanagarwal1211 Ideally we should not let users to give additional points to the same functionality,. you can add different PR, but not recommended to give levels. so removing this levels.

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir these two were completely different first bug is because the website shifted to next js so that its color is not correctly given and the second bug is for on moving on different routes the color is not remaining stable please see the  description i wrote in this pr . Sir this is not fair with me you can review all my codes i am doing all fair and my levels are removed after sometime . Sir i have given more than 30 hours to this repo . You can confirm it from project owner .

**Comment by Ayushmaanagarwal1211** [comment]
and sir https://github.com/MAVRICK-1/e-commerce_website/pull/379/files i saw on this repo i improved the whole seo of the website by doing lot of research about seo and write the code but my level decreases to level 1

**Comment by sanjay-kv** [comment]
> @sanjay-kv Sir these two were completely different bugs first bug is because the website shifted to next js so that its color is not correctly given and the second bug is for on moving on different routes the color is not remaining stable and i solved two more bugs with second pr please see the description i wrote in this pr and the second pr you can review all my codes i am doing all fair contributions on this repo and my levels get removing after sometime . Sir i have given more than 30 hours to this repo . You can confirm it from project owner sir website updates day by day so it will produce more and more new bugs day by day sir so i need to solve that sir i have all chats with the project owner about the project and contributions i did so i am not doing anything unfair sir .

I was asking the same, Nw. those should be level to 1

**Comment by nishant0708** [comment]
Bro I know your feeling about points reduction been there ..but about these gap I have code formatter so these get automatically fixed that was not intended..

**Pull request merged**
