### PR TITLE
add proper subscribe to newsletter section and colour of night mode as per figma design 

### LINKED ISSUE #507: Feat : enhancement of landing page
### Describe the feature

doing it according to the figma dsign

### Add ScreenShots

Screenshot 2024-06-19 173645
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #507 
 added proper subscribe to newsletter section and colour of night mode as per figma design . 
font of helpops was not matching with the figma design earlier and provided proper shadow effect according to figma design .

BEFORE :
image

image

AFTER
image

image

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 I have observed the figma very closely and I think I have  more close to figma design I have made sure that font and box shadow match with the figma design .

**Comment by ANKeshri** [comment]
@mdazfar2 since I was observing the figma design and trying to achieve the same effect it took me more time and i have made sure that my fork is also sync .

**Comment by ANKeshri** [comment]
@mdazfar2 please review it once and merge my pull request .

**Comment by mdazfar2** [comment]
@ANKeshri please don't work on `subscribe` thing and cancel that changing

### It not looks good as an current onew

<br>

image

<br>

### only create pr for this one 👇

<br>

image

**Comment by ANKeshri** [comment]
> @ANKeshri please don't work on `subscribe` thing and cancel that changing
> 
> ### It not looks good as an current onew
> 
> image
> 
> 
> ### only create pr for this one 👇
> 
> image

**Comment by ANKeshri** [comment]
> > @ANKeshri please don't work on `subscribe` thing and cancel that changing
> > ### It not looks good as an current onew
> > image
> > ### only create pr for this one 👇
> > image

@mdazfar2 this one is created by me .

image

 sir as you see i have use the same font of what is used in figma design and also added the border shadow which was not present . 


image
this is earlier one which do not contain box shadow and font is also not according to figma design .

image
this is the figma design ehat you have provided

**Comment by mdazfar2** [comment]
Ok I'll see how this is

**Comment by mdazfar2** [comment]
@ANKeshri give margin from right and left align properly

<br>

image

**Comment by ANKeshri** [comment]
> @ANKeshri give margin from right and left align properly
> 
> 
> image

@mdazfar2 working on it

**Comment by mdazfar2** [comment]
@ANKeshri indeed

**Comment by ANKeshri** [comment]
image
@mdazfar2 is this what you were asking to do

**Comment by mdazfar2** [comment]
@ANKeshri Please don't feel bad :)

- This looks a little weird. Leave it for now; I will tell you in the future if there is a need regarding this. Please try to work on another issue.

**Comment by ANKeshri** [comment]
> @ANKeshri Please don't feel bad :)
> 
> * This looks a little weird. Leave it for now; I will tell you in the future if there is a need regarding this. Please try to work on another issue.

ok

**Pull request closed without merging**
