### PR TITLE
Bottom top button

### PR DESCRIPTION
**Pull request by Varsani2520**
i set the bottom to top button in all the screen like mobile,tablet,laptop ,desktop etc also i design the button :
this is full screen look:
image
this is responsive screen:
image

@mdazfar2 

check it and merge it #253 and closed it

### CODE REVIEW

**Comment by Varsani2520** [comment]
Yes @mdazfar2

**Comment by Varsani2520** [comment]
you tell me i give you level 3 in next pr but you dont give why ?

**Comment by mdazfar2** [comment]
> you tell me i give you level 3 in next pr but you dont give why ?

I never forget my tongue. @Varsani2520 

<br>

- I have designed a new website for HelpOps-Hub, our team is working on it. Will you please help us?



<br>
 
It is how homepage looks like

**Comment by Varsani2520** [comment]
new home page is good but not very good

**Comment by Varsani2520** [comment]
if you assign me and merged the pr then i will help you

**Comment by Varsani2520** [comment]
Hey @mdazfar2 ,tell me how can i help you ?

**Comment by Varsani2520** [comment]
can i design a your new home page ?

**Comment by mdazfar2** [comment]
> can i design a your new home page ?

@Varsani2520 It is very difficult to tell here on GitHub. Can you join me on [LinkedIn](https://linkedin.com/in/md-azfar-alam/) or [Discord](https://discord.gg/UWTrRhqywt) where we can talk easily?

**Comment by Varsani2520** [comment]
yes

**Pull request merged**
