### PR TITLE
Fixes all issues

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #647 

I have style sponsor button give new look to it.
Make mode change svg under one button like sponsor.
Now navbar looks good.

https://www.loom.com/share/697338d2e85a4c07ab6d4fe1fe479223

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Consider this PR this is updated you can check it !

**Comment by mdazfar2** [comment]
@zalabhavy I saw that you create Pull Requests again and again, which doesn't look professional. If you update and sync the fork, it will be triggered here automatically. Please update and sync the fork again as there are some changes with our web.

**Comment by zalabhavy** [comment]
@mdazfar2 It is already updated and sync.
After that I create this PR.

**Comment by mdazfar2** [comment]
No bro @zalabhavy, it is not updated to the current version of the website. I think your `main` branch is updated, but you need to update those branches which create PRs. That's why on my side, it shows that everything is updated. Hope you understand.

**Comment by zalabhavy** [comment]
@mdazfar2 Another commit in this PR is created Please authorize it and check it !

**Comment by mdazfar2** [comment]
ok I'll see it in some time@zalabhavy

**Review by mdazfar2 — APPROVED** [review]
Finally you did it! Thanks a lot @zalabhavy

**Comment by zalabhavy** [comment]
@mdazfar2 I have done many mistakes today but end of the day i got lots of learnings !
Thanks to you for explaining !

**Pull request merged**
