### PR TITLE
Added sponsor button to website

### PR DESCRIPTION
**Pull request by pandeyji711**
@mdazfar2
###  I have added Sponsor button 

Uploading Recording 2024-06-02 204542.mp4…

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
Looks good to me 🚀

**Comment by sanjay-kv** [comment]
@mdazfar2 be careful when giving level 3, its just a random comment on random PR. 
so only high level changes should be consider level3

**Comment by mdazfar2** [comment]
> @mdazfar2 be careful when giving level 3, its just a random comment on random PR. 
> so only high level changes should be consider level3
> 


@sanjay-kv Ok, I will take care of it from now on.

**Comment by sanjay-kv** [comment]
@mdazfar2 kindly add me into the repo , so i can manage the labels.

**Comment by pandeyji711** [comment]
@sanjay-kv From now on, I'll be raising issues first. Sorry for any inconvenience this may have caused.

**Pull request merged**
