### PR TITLE
#1322 #add A New Terms and Conditions page

### PR DESCRIPTION
**Pull request by KiranBaliga**
This pull request introduces a new Terms and Conditions page located at the bottom of the homepage of HelpOps-Hub project, addressing issue #1322.

Changes Made:

Created TermsAndConditions.js in the pages folder to outline the terms and conditions for using the HelpOps-Hub website.

Added a corresponding CSS file in the stylesheets folder for custom styling.

Updated the Footer.js component to include a link to the Terms and Conditions page.

This page aims to provide users with clear information about their rights and responsibilities when using the HelpOps-Hub services. Please review the changes and let me know if there are any further adjustments needed.

Thank you!

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @kiranBaliga, thank you for the pull request. Since we don't use CSS, please convert it to Tailwind CSS.

**Comment by KiranBaliga** [comment]
A commit has been made to reflect the requested changes.

**Comment by mdazfar2** [comment]
Hey @KiranBaliga, I cannot see your changes here, and there is an error after running your branch through Git CLI on my local machine. Please look at the video below as proof.

<br>


https://github.com/user-attachments/assets/9ecc4444-42fb-4fc4-b654-7d42f913a3fc

**Comment by mdazfar2** [comment]
Hey @KiranBaliga, I cannot see your changes on deployment here, and there is an error after running your branch through Git CLI on my local machine. Please look at the video below as proof.

<br>


https://github.com/user-attachments/assets/ad5ba788-ab25-40e1-91f1-628a2936b301

**Comment by KiranBaliga** [comment]
Closing the PR for now.

**Pull request closed without merging**
