### PR TITLE
Fixed content overflow in cards Home page

### LINKED ISSUE #1003: BUG: Content overflow on Home page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Home page has a content overflow below 1024px 

[home.webm](https://github.com/user-attachments/assets/daa8230d-f22d-48af-896f-2a8ff59ad5c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Amruta7203**
Fixed #1003 

[content.webm](https://github.com/user-attachments/assets/8968f48c-0825-4707-84c0-558d4b752a09)

### CODE REVIEW

**Comment by Amruta7203** [comment]
@mdazfar2 I have fixed the content overflow issue... pls check the screen video attached..

**Comment by mdazfar2** [comment]
Hey @Amruta7203, you made changes to our UI, but it is not as shown on our deployed website. The middle two cards are not aligned with the other side cards, which looks weird.

<br>

image

**Comment by Amruta7203** [comment]
I'm not actually getting what you are trying to say @mdazfar2 .. The cards look in a line as expected.. Could you pls explain the issue more clearly?

**Comment by mdazfar2** [comment]
@Amruta7203 
please look at the below screenshot i want exactly this one 

<br>

image

<br>

- But here, as shown below, you made changes that don't look good. If you compare them to our current deployed website, you will easily see the difference and understand my point. 🔻

<br>

image

> I hope this time you understand what i want to say.

**Comment by Amruta7203** [comment]
Oh okay.. Got it.. I'll make required the changes..

**Comment by Amruta7203** [comment]
@mdazfar2 I have made the changes:

[new.webm](https://github.com/user-attachments/assets/7f66659e-b9c4-490c-b847-b30ab64408f7)

**Comment by mdazfar2** [comment]
@Amruta7203,
I'm noticing potential deployment errors with your changes. To avoid any issues and ensure your changes appear on the live website, I can't merge this pull request at the moment.

<br>

image

**Comment by Amruta7203** [comment]
I have not changes anything in imports and exports though @mdazfar2 ..

**Comment by mdazfar2** [comment]
> I have not changed anything in imports and exports though @mdazfar2 ..

@Amruta7203 then why this error will come please try to resolve the error according to the display of the above screenshot.

**Comment by Amruta7203** [comment]
Could you pls run it again @mdazfar2 and let me know if the error still persists?

**Comment by mdazfar2** [comment]
@Amruta7203 did you change anything? Actually, I already ran it and will tell you after deploying your changes.

**Comment by Amruta7203** [comment]
> @Amruta7203 did you change anything? Actually, I already ran it and will tell you after deploying your changes.

I did try to install all the dependencies and commit it but got many conflicts.. if the error is still there pls guide me on resolving it..

**Comment by Amruta7203** [comment]
@mdazfar2 Why my PR was closed..?

**Comment by Amruta7203** [comment]
> Already solved

But I was assigned to work on it right?

**Comment by mdazfar2** [comment]
@Amruta7203 I apologize, but it was already done by someone else's PR. When someone solved another bug, they realized that the homepage was not responsive, so they fixed it. However, it was not solved by the assigned person. I hope you understand what I mean. Please don't be discouraged!

**Pull request closed without merging**
