### PR TITLE
Added "Scroll down progress bar"

### LINKED ISSUE #608: ✨ Feat: Add a "Scroll down progress bar"
### Describe the feature

Hey @mdazfar2 

I would like to suggest adding **a scroll down progress bar** to the website to enhance user experience. 
- A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. 
- This feature can be especially helpful for long pages blogs and articles.

### Add ScreenShots

- **Like this**

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @mdazfar2 | closes #608 

I have added the "Scroll down progress bar" to the website

**Changes I made:**
- Created `progress.js` file
- Included logic to reset the scroll progress on page navigation using Next.js's `usePathname` hook.
- Added CSS in `global.css`

This improves navigation efficiency and overall user experience, particularly on lengthy pages.

(Note: if we try to match background theme then the bar leads to blending issue so tried to use closest color as possible)

https://github.com/mdazfar2/HelpOps-Hub/assets/101971980/19f4d4ff-ea9c-4f73-a282-250fec3c99c8

Please review the changes and consider merging this pull request, 
Also I request you to add **level 2** label if possible, Thank You!!

### CODE REVIEW

**Comment by mdazfar2** [comment]
hey @MastanSayyad it doesn't looks good as usual could you remove these all changes and try to change the color of this one:

<br>

image

**Comment by MastanSayyad** [comment]
its Vertical Scroll-bar @mdazfar2

**Comment by MastanSayyad** [comment]
Look at the top there is progress bar @mdazfar2

**Comment by MastanSayyad** [comment]
@mdazfar2 okay got it, you mean remove the scroll bar and adjust the color of vertical scroll-bar

**Comment by mdazfar2** [comment]
> @mdazfar2 okay got it, you mean remove the progress bar and adjust the color of vertical scroll-bar

yes @MastanSayyad

**Comment by MastanSayyad** [comment]
@mdazfar2 done the changes

image


image



https://github.com/mdazfar2/HelpOps-Hub/assets/101971980/badcd8bb-5d31-4e6f-b151-42450de9b919

**Comment by mdazfar2** [comment]
@MastanSayyad in dark mode it doesn't change

**Comment by MastanSayyad** [comment]
which browser are you using? @mdazfar2

**Comment by mdazfar2** [comment]
@MastanSayyad
Edge

**Comment by MastanSayyad** [comment]
@mdazfar2 ensure you clear your browser cache , in chrome browser it works fine, still I'll try to customize it for edge compatibilty

**Comment by MastanSayyad** [comment]
@mdazfar2 this should work fine, if not then try chrome browser

**Comment by mdazfar2** [comment]
> @mdazfar2 this should work fine, if not then try chrome browser

@MastanSayyad It is also doesn't work in chrome

**Comment by MastanSayyad** [comment]
In only dark mode right?

**Comment by mdazfar2** [comment]
@MastanSayyad 
yes

**Comment by MastanSayyad** [comment]
okay, got it!

**Comment by MastanSayyad** [comment]
@mdazfar2 this should work fine

**Comment by MastanSayyad** [comment]
@mdazfar2 pls merge this PR

**Comment by mdazfar2** [comment]
@MastanSayyad kindly resolve your conflict then i can deploy your changes

**Comment by MastanSayyad** [comment]
@mdazfar2 Resolved

**Comment by MastanSayyad** [comment]
@mdazfar2 conflicts are resolved

**Comment by mdazfar2** [comment]
hey @MastanSayyad I apologize, but I need to close this pull request for now. Please don't be discouraged! We can work together ono another issue if you want :)

**Comment by MastanSayyad** [comment]
It's fine, I can understand! @mdazfar2

**Pull request closed without merging**
