### PR TITLE
UI of AboutUs page

### PR DESCRIPTION
**Pull request by alpharsh**
Before:
Screenshot 2024-06-17 003103

After: 
Light mode:
Screenshot 2024-06-17 003120
Dark mode:
Screenshot 2024-06-17 003139

closes: #456

### CODE REVIEW

**Comment by mdazfar2** [comment]
@alpharsh The color is not black, and the font size you applied is awesome, but please revert the text color to the previous one.

<br>

image

**Comment by alpharsh** [comment]
@mdazfar2 the black color is fixed

**Comment by mdazfar2** [comment]
@alpharsh update your sync fork

**Comment by alpharsh** [comment]
@mdazfar2 done sync

**Comment by mdazfar2** [comment]
@alpharsh In dark mode it is grey in text not white, please revert the text color to the previous one.

**Comment by alpharsh** [comment]
@mdazfar2 done

**Review by mdazfar2 — APPROVED** [review]
Thank you @alpharsh 


- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Pull request merged**
