### PR TITLE
Fixed responsive of contributor section

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've created a responsive contributor section for the website .
closes : #154 

Hii there I attached the demo video please see i

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/6d8cf1dc-7521-41f3-b142-8b1211d460a8

### CODE REVIEW

**Review by mdazfar2 — COMMENTED** [review]
@Ayushmaanagarwal1211 Great work but i want the intro of `our team is good at the alignment of left` as desktop view

image

- It is good at it's place, just leave it there on the desktop view, Do you understand na what I want to say?

**Comment by Ayushmaanagarwal1211** [comment]
Yes i am correcting it

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  can you check it again i fixed it 


https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/0ffff20c-1763-454f-991d-328837bcea90

**Review by mdazfar2 — APPROVED** [review]
Thank you @Ayushmaanagarwal1211

**Comment by mdazfar2** [comment]
Hi @Ayushmaanagarwal1211 just i noticed that you are removed color inside from the card color
<br>

image

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am seeing what is happening

**Comment by Ayushmaanagarwal1211** [comment]
oh i found the mistake please wait i will fix it

**Comment by mdazfar2** [comment]
> oh i found the mistake please wait i will fix it

<br>
@Ayushmaanagarwal1211 please as soon as complete this issue you can raise an issue on that

**Comment by Ayushmaanagarwal1211** [comment]
Actually I already raised pr please see that

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir can i please know why you removed the level

**Comment by sanjay-kv** [comment]
image

image
this is basically creating multiple PR to do one single tasks. already level 2 is given for other PR.

**Comment by Ayushmaanagarwal1211** [comment]
Sir this is due to because this website contains multiple pages landing page , contributor page , resources page faq page , about us page and contact us page so i did responsive every pages except contributor page because this contains many cards that's why

**Comment by Ayushmaanagarwal1211** [comment]
And i see Sir many levels are reduced or removed on this repo sir i can prove my authenticity for each pr you can confirm it  from @mdazfar2  i connected with him on discord from where we did too many discussion from the owner of the repo i can send every screenshot to you

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv please have a look ?

> @sanjay-kv Sir the website consists of multiple pages including a landing page, a contributor page, a resources page, an FAQ page, an About Us page, and a Contact Us page. I have ensured that all pages are responsive, except for the contributor page due to its high complexity
> 
> You can review all discussions and changes made in this pull request. Additionally, please note that the repository contains two versions of the website: the old one and the new one. The pull request for the Contact Us page's responsiveness belongs to the new website. Previous pull requests are for the old website. You can verify this in the repository folder, which contains both Website 1.0 and Website 2.0.

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv Sir the website consists of multiple pages including a landing page, a contributor page, a resources page, an FAQ page, an About Us page, and a Contact Us page. I have ensured that all pages are responsive, except for the contributor page due to its high complexity

You can review all discussions and changes made in this pull request. Additionally, please note that the repository contains two versions of the website: the old one and the new one. The pull request for the Contact Us page's responsiveness belongs to the new website. Previous pull requests are for the old website. You can verify this in the repository folder, which contains both Website 1.0 and Website 2.0.

**Comment by Ayushmaanagarwal1211** [comment]
I noticed sir that many levels have been reduced or removed from the pull requests in this repository. I can prove my authenticity for each and every pull request. You can confirm this with mdazfar2, with whom I have connected on Discord. We have had numerous discussions with the owner of the repository regarding these changes.
If you have any concerns about spamming or any inappropriate behavior, please let me know sir . I am ready to provide proof for all my contributions.

**Comment by sanjay-kv** [comment]
i can only change to level1, as I have personally seen this code changes. 
I understand your concern on points, the thing is many have reported the same issues to us. 

So what if contributors start replicating the same patterns? like a website with 10 pages, make it responsive page by page, and get level 2. this will lead to spamming.

**Pull request merged**
