### PR TITLE
Added FAQ's Page 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added a FAQ's page by taking some common question and answers .
If You didn't like something please let me know i will do that .
If you like my work please give us level 3 if you found it suitable for that .

closes : #113 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/c1107e67-7117-41a6-9248-69324a0083ac

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
Thank you @Ayushmaanagarwal1211 but try to update it more by adding some attractive sentence you can create new issue for it if you want.

**Comment by Ayushmaanagarwal1211** [comment]
Ok Sure means i have to add more question and answers .

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 leave it for now. Let you know if there is need in future

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by mdazfar2** [comment]
> Ok Sure means i have to add more question and answers .

<br>

@Ayushmaanagarwal1211  Yes, go ahead and create an issue for it. Try to explain each question's answer in a more detailed and attractive way.

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Pull request merged**
