### PR TITLE
Fixed navbar appear effect

### PR DESCRIPTION
**Pull request by Utsavladia**
issue #538 
Added the Navbar at top and adjusted padding on home to have proper look..
Also auto formatting code made the code more readable

https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/6263832f-ddca-48d5-80ce-6f32c3394da5

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Utsavladia when we switch some page then it looks like that which looks not good

<br>

image

**Comment by Utsavladia** [comment]
@mdazfar2  
sure,
I will try to fix it.

**Comment by mdazfar2** [comment]
@Utsavladia sure

**Comment by Utsavladia** [comment]
@mdazfar2 
Do you want me to add paddings at top in rest 3 pages to make it look same as above with this new navBar functionality or
you want me to make navBar disappear when user clicks on any page kepping the padding same

**Comment by mdazfar2** [comment]
No @Utsavladia 
See,  it is working on the homepage. It should work on the whole page like homeoage and should be on by default at switch time as it was before. Then, when you scroll down, that floating navbar appears.

**Comment by Utsavladia** [comment]
@mdazfar2 

It is workinng same as home page.. I think we need padding at top to make it look better... what you say

https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/7fa4be5f-875f-4ab4-a6f9-2be28da0cac8

**Comment by mdazfar2** [comment]
No @Utsavladia,
- **I want this when user switch any page-**
<br>

image

<br>

and when user scroll down then the floating animation will show hope this time you understand
> Still don't understand? No problem, you can ask me again and I will try my best to describe.

**Comment by mdazfar2** [comment]
@Utsavladia Actually Next.js component-based architecture you don't have to make for individually every pages just one component is applied to every pages automatically if you can't do it no problem i can assign it anyone that's why you can learn something new about that.

**Comment by Utsavladia** [comment]
@mdazfar2 
I hope this is the desired result 



https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/7f2eaa15-ad34-47d5-9dd7-6213da20bb20

**Comment by mdazfar2** [comment]
@Utsavladia switch page from floating navigation then shown me how it is looks like

**Comment by Utsavladia** [comment]
sure @mdazfar2 

https://github.com/mdazfar2/HelpOps-Hub/assets/124615886/8a376993-655b-4525-a9e2-9bc9e13a1d4f

**Comment by mdazfar2** [comment]
@Utsavladia Yes, this is exactly what I want, but when we switch to the contact page, it looks like that. Please resolve this also.

<br>

image

**Comment by Utsavladia** [comment]
@mdazfar2 
In the latest commit i fixed it already

This is the latest view
image

**Comment by mdazfar2** [comment]
@Utsavladia please update sync fork and resolve conflicts

**Comment by Utsavladia** [comment]
sure
I resolved all conflicts

**Comment by mdazfar2** [comment]
@Utsavladia
 I don't have a laptop right now, I'll check it out and merge it after a while.

**Comment by mdazfar2** [comment]
@Utsavladia it is not in center please compare the current deployed website with your local machine you will get difference

<br>

image

**Comment by Utsavladia** [comment]
@mdazfar2 
sure
I fixed it the hero

**Review by mdazfar2 — APPROVED** [review]
you are awesome @Utsavladia ✨

**Comment by Utsavladia** [comment]
@mdazfar2 
thank you so mush I literally wanted it to look perfect and close to the desired output 😊

**Comment by mdazfar2** [comment]
@Utsavladia Can you do one more thing? If the navigation floats, the color doesn't look good. Can we change the gradient color to orange and yellow? If you agree, then raise an issue on that.

<br>

image

**Comment by Utsavladia** [comment]
@mdazfar2  Sure 
I am raising a new issue for this .
Please tell me the exact color you want

**Comment by mdazfar2** [comment]
> @mdazfar2 Sure I am raising a new issue for this . Please tell me the exact color you want

@Utsavladia 
gradient of Orange and yellow

**Comment by Utsavladia** [comment]
@mdazfar2 
Great I have raised the issue

**Comment by mdazfar2** [comment]
hey @Utsavladia you may have made some changes in `Dark Mode`. Dark mode is not working properly. Please check it out.

**Pull request merged**
