### PR TITLE
changed footer

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've changed footer as given please check it 

Screenshot 2024-06-06 215117

### CODE REVIEW

**Comment by mdazfar2** [comment]
hey @Ayushmaanagarwal1211 You have enlarged this photo as i have sent it in the screenshot. Look how small it is and try to write in the same font. write in such away that it looks like attractive

**Comment by Ayushmaanagarwal1211** [comment]
Ok changing

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  I've updated please check the font size

**Comment by Ayushmaanagarwal1211** [comment]
I used 18px as font size

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 also trying to resolve the below screenshot-

<br>

image

<br>

According to highlight box try to fix "feedback" and "feedback image" also

**Comment by Ayushmaanagarwal1211** [comment]
Ok means i have to move the images and form to slightly right

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 

image

not looks good to me

**Comment by Ayushmaanagarwal1211** [comment]
Can you tell me the changes

> @Ayushmaanagarwal1211
> 
> image
> 
> not looks good to me

**Comment by mdazfar2** [comment]
> Can you tell me the changes
> 
> > @Ayushmaanagarwal1211
> > image
> > not looks good to me

@Ayushmaanagarwal1211 do small size of footer 

<br>

image


<br>

here it is

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 update sync fork and pull push before sending pr

**Comment by Ayushmaanagarwal1211** [comment]
I have set the same font size as 0.875rem and line height by 1.175rem as in the given link

**Comment by mdazfar2** [comment]
> Ok means i have to move the images and form to slightly right

- exactly @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 It is deployed failed try to fix it again and create pr

image

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot 2024-06-06 231408
I think it's because of free version of vercel only gives 100 deployed per day that's why it is showing error

**Comment by mdazfar2** [comment]
> Screenshot 2024-06-06 231408 I think it's because of free version of vercel only gives 100 deployed per day that's why it is showing error


---

after 30 minutes i can use it again right?

**Pull request merged**
