### PR TITLE
[FIX] Unnecessary spacing in active filter marker

### LINKED ISSUE #1375: Unnecessary spacing in active filter marker
### Description

As you can notice in the attached screenshot that the border bottom marking the active filter has an unnecessary space, which does not look good in mobile view of the application.

Please assign me this issue under level2 gssoc gssoc-ext hacktoberfest hacktoberfest-accepted...I'll be happy to work on it 💯

### Screenshots

IMG_7532

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by roushan-code**
## Description

I have remove unnecessary spacing of border bottom marking the active filter. 

<br/>

## Related Issues

- Closes #1375

<br/>

## Screenshots / videos (if applicable)

2024-10-2322-02-39-ezgif com-crop

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @roushan-code, please check your changes again; they are not correct and may be problematic. I have sent the screenshot; please see it below. Please don't be discouraged, but I cannot merge this pull request. **Thank you!**



image

**Comment by roushan-code** [comment]
Hey @mdazfar2 , Could you please review it again?

**Comment by mdazfar2** [comment]
@roushan-code, I don't understand what you changed. I don't see any changes on the deployment link; the website looks fine on my side. Please check the screen recording below as proof.



<br/>


https://github.com/user-attachments/assets/02e1e1ec-854a-4d42-af24-a7a0da26ec6a

**Comment by roushan-code** [comment]
Hey @mdazfar2, I have attached a video below. Is this you want?

### video
https://github.com/user-attachments/assets/1b1455e5-4bd3-46fb-a94b-ab4a31894bb3



 Actually Firstly, I was solving the issue that is mention in issue number #1375 with the screenshot given below.
issue

**Pull request closed without merging**
