### PR TITLE
Enhanced the theme 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've enhanced the theme by  adding perfect gradually increase color variants of orange , by changing some of the css for loading and scripts according to the priority .

closes :  #528 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/fde19236-d4d7-4294-9eff-ce089b45e8de

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 There doesn't seem to be any change in this.

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Please check again is it visible now

**Comment by mdazfar2** [comment]
No @Ayushmaanagarwal1211

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Even in the video you provided, there isn't different anything?

**Comment by Ayushmaanagarwal1211** [comment]
Please wait i will check

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/b5bce5dd-63d6-4572-90e2-4de27d83939c

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  please see the video

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Even in the video you provided, there isn't different anything?

**Comment by Ayushmaanagarwal1211** [comment]
> @Ayushmaanagarwal1211 Even in the video you provided, there isn't different anything?

I changed the color from top to bottom like that 
original 
Screenshot 2024-06-20 141004

after 
Screenshot 2024-06-20 141014

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Updated  .

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 can you do one more thing:



### It is a mixture to the background color. Please add some shadow and try to add a light color that doesn't seem mixed.
<br>

image

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Ok doing

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot 2024-06-20 142111

@mdazfar2  please check

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Light colour will look better instead of full orange

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  in Newsletter box

**Comment by mdazfar2** [comment]
> @mdazfar2 in Newsletter box

yes

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot 2024-06-20 142707

Is this ok

**Comment by Ayushmaanagarwal1211** [comment]
Ok more light

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 can we add gradient of orange and yellow how is it looks like?

**Comment by Ayushmaanagarwal1211** [comment]
Wait i am sending you

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot 2024-06-20 142919

like that

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 previous one was good

### create pr of this one 👇

<br>

image

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Done updated

**Review by mdazfar2 — APPROVED** [review]
Thank you @Ayushmaanagarwal1211

**Pull request merged**
