### PR TITLE
Done changes for Signup/Login, OTP & Profile 

### LINKED ISSUE #854: Feat: Add the missing close icon for relevant components
### Describe the feature

In the process of upgrading our website, it seems like the close icon for some components got removed......I want to add the icon back for all relevant components

### Add ScreenShots

image (1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### LINKED ISSUE #859: Feat: Make the Signup/Login page Responsive
### Describe the feature

Currently our Login/Signup components are not responisve for Mobile-S,M,L screens......I would like to add proper responsiveness for the respective screens

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/843c7095-123c-419d-afdd-02498ac05fd2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
## Description

Fixes #859 
Fixes #854 

- Added the missing `close-btn` for `Signup`
- Retained the classNames for `Signup`, `Login`, `OTP` and `Profile` for proper responsiveness
- Refactored some classes' Tailwind CSS 

## Video

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/7aac412f-0b11-4ba1-81fb-8aa0e835c579

### CODE REVIEW

**Comment by Asymtode712** [comment]
@mdazfar2 Please review and merge this PR

**Comment by mdazfar2** [comment]
@Asymtode712 In the screenshot below, within the left red highlighted square, please update the text to "Forget Password" on a single line. Then, on the right side within the other red highlighted square, update the text to "New here? Sign Up Now" on a single line.

<br>

image

<br>

> Hope you understand

**Comment by Asymtode712** [comment]
@mdazfar2 

- Aligned the p items in `Login` page
- The placeholder text is looking fine in my local deployment server

**Comment by mdazfar2** [comment]
@Asymtode712,

It seems there might be a misunderstanding.  When comparing your deployment to the current version, you may notice that the default text you entered appears bold, which isn't ideal visually.  Could you please take a look and adjust the formatting as soon as possible?

**Pull request closed without merging**
