### PR TITLE
BUG:Want to Fix Alignment of Eye Icon + Want to Signup Not Saying at same place on different Screen #772

### LINKED ISSUE #772: BUG:Want to Fix Alignment of Eye Icon + Want to Signup Not Saying at same place on different Screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

image
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by nishant0708**
Fixed #772 

Before::
Screenshot 2024-07-02 120118

Screenshot 2024-07-03 030028

After::

Screenshot 2024-07-03 032713
Screenshot 2024-07-03 033941

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @mdazfar2 please review this pr

**Comment by mdazfar2** [comment]
@nishant0708 did you update sync fork?

**Comment by mdazfar2** [comment]
@nishant0708 In mobile view responsive it looks like weird as compare to the current once please resolve this

<br>

image

**Comment by nishant0708** [comment]
image
hey @mdazfar2 it is fine now please check and let me know changes

**Comment by mdazfar2** [comment]
@nishant0708 You might not have updated your sync fork. Please update it.

**Comment by nishant0708** [comment]
hey @mdazfar2 check it now

**Review by mdazfar2 — APPROVED** [review]

**Pull request merged**
