### PR TITLE
Created the newsletter with proper functioning and validation pop up

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added the proper pop up and proper functioning of the newsletter 

i enhanced the design of the search bar as well
Now on submitting the user will see proper message in proper pop up that will looks amazing and also indicate the user about the current state of his/her request .

closes : #668 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/59b76ac8-3b32-49f6-a690-d68dd6c4f1e6

### CODE REVIEW

**Comment by shreyash3087** [comment]
Kindly make sure that you have added the popup card for this also- #690 

It should show You are already subscribed to the Newsletter! in popup as well

**Comment by Ayushmaanagarwal1211** [comment]
Bro i did discussion with afzar aslam for the same

**Comment by shreyash3087** [comment]
yes so add your popup for that message as well since its just added

**Comment by Ayushmaanagarwal1211** [comment]
@shreyash3087  bro i know that i have to add  it was creating conflict that's why i will do that after merging this
Bro i know what i am doing @mdazfar2  he know

**Comment by shreyash3087** [comment]
@Ayushmaanagarwal1211  Alright thats fine then

**Review by mdazfar2 — APPROVED** [review]
That's amazing!
- Try to resolve for already subscribed and will give you the loading effect and will change with current ones.

**Pull request merged**
