### PR TITLE
properly apply dark mode in resources page 

### LINKED ISSUE #559: BUG: FIX day and night mode in all the resources
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in the resourse the page is same for the dark and light mode . 

BEFORE : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/de7dd607-588b-40a6-a885-5da9d23c3a9d

AFTER 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/c5d0eb37-df69-4f43-aa5f-675f4764eba9

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #559 

in all the pages of resources dark mode has been added . Here i have shown in few resources but I have made sure that in all the resources page dark mode is working .

BEFORE :  

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/c2b1e930-2566-4406-b0bd-274d5b6f68fd

AFTER :  

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/245f8408-b3e0-4f68-b3c3-636b31acc2a4

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 please review this once i don't know whay was problem with that pr . I am new comer , I have lot to learn . I am sorry .

**Comment by mdazfar2** [comment]
@ANKeshri The same problem which was occurring in the previous time is occurring again.

**Comment by ANKeshri** [comment]
you see the video i have attached @mdazfar2

**Comment by mdazfar2** [comment]
@ANKeshri, it appears differently on my deployment server. See the screenshot for reference.

<br>

image

**Comment by ANKeshri** [comment]
> @ANKeshri, it appears differently on my deployment server. See the screenshot for reference.
> 
> 
> image
> 
> 
> * I think we might need to wait a while on this. There could be an issue with Vercel.

@mdazfar2 it might be,  from my end i have checked many times , i have visited all pages , all were fine .

**Review by mdazfar2 — APPROVED** [review]

**Comment by mdazfar2** [comment]
@ANKeshri, I merged the changes, but I'm not seeing the expected behavior yet. Unfortunately, it seems it can't be deployed at this time. By the way thank you so much for your patience and hard work on this. :)

**Comment by ANKeshri** [comment]
@mdazfar2 changes have been reflected in the site as you can see in below video .


https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/881db3e4-daf7-49e6-9168-62a2a86998e7

all things are working fine . don.t worry there may be an issue with deployment . 

thank you

**Comment by ANKeshri** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/91b7209e-870c-4ed2-97e4-58098ddfde91

@mdazfar2 see in this also working fine . I have viewed it in mac .

**Comment by mdazfar2** [comment]
Ooh I guess there is some CDN's problem

**Comment by ANKeshri** [comment]
> Ooh I guess there is some CDN's problem again thank you so much @ANKeshri

in my phone also it is working

**Comment by ANKeshri** [comment]
Screenshot_2024-06-22-01-21-26-759_com android chrome

**Pull request merged**
