### PR TITLE
Bug: Fixed Homepage's Responsiveness

### LINKED ISSUE #628: BUG:Making the Whole Landing Page Responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Currently the Landing Page of Helpops Website lacks Responsiveness for Mobile Devices.The page should be compatible with all the devices, as it is the landing page,the entry point for all users on helpops-hub it should be a priority to make it responsive for all devices

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/abd42251-12f1-42f9-a500-c75ca134cfca

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR fixes the Responsiveness Issue for the Landing Page and ensures that the website is compatible with all devices.

**Issue Mentioned:**

Closes #628 

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/f413e1b6-ee32-4e84-8143-f1339a8d0b18

**DarkMode:**

Screenshot (78)
Screenshot (80)

**Additional Context:**

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@mdazfar2 kindly review

**Comment by mdazfar2** [comment]
@shreyash3087 please update sync fork

**Comment by shreyash3087** [comment]
done

**Review by mdazfar2 — APPROVED** [review]
Looks good to me ✨

**Pull request merged**
