### PR TITLE
Created Contact Us page 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added the contact us page for the website 
It needs just an api key steps to get :- 
1. Go to https://web3forms.com/
2. create account by just entering any email
3. You got the api key on your gmail account 
4. That's all you can directly put that api key to line number 81 of contact.html 
5. Now When any user hits on submit the message directly goes to your gmail account

closes : #111

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/ec20f8bc-5f05-43cf-8bda-d8c05af94247

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 The Web3form doesn't work on Vercel. I'll implement it. Try to enhance it on the backend with MongoDB, Node.js, or anything you want, but do not use Web3form.

- You can check out one of my friend's portfolio. He also used Web3form and got an error. Please visit the "Contact Us" section in the portfolio [here](https://www.raviranjan.live/).

**Comment by Ayushmaanagarwal1211** [comment]
Ok i will implement it using some other way

**Comment by Ayushmaanagarwal1211** [comment]
Can i implement backend server and use node mailer for that

**Comment by mdazfar2** [comment]
> can i use emailjs
> 

@Ayushmaanagarwal1211 Do one thing: leave the "Contact Us" section and try to add a backend to the "Feedback" section because users can contact us on LinkedIn as well.

- you can use emailjs on feedback.

- But after submitting, to whom will the mail go? Please ask me for details once. If you want to work on it.

**Comment by Ayushmaanagarwal1211** [comment]
Ya sure i will raise issue for that

**Comment by mdazfar2** [comment]
Sure

**Pull request closed without merging**
