### PR TITLE
Added Comment button

### LINKED ISSUE #989: Feat: Make comment button for post.
### Describe the feature

Comment button post comment.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by zalabhavy**
Fixes #989

In localhost i am not able to see this but as i look in react-tailwind online compiler it is looks good.

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Please check it and merge !

Thank You !

**Comment by mdazfar2** [comment]
@zalabhavy please update sync fork

**Comment by mdazfar2** [comment]
@zalabhavy there is work on the backend, so you have to update the sync fork again. Sorry for the repeated requests; I can't do anything about it and please update me once that you have synced.

**Comment by zalabhavy** [comment]
@mdazfar2 No Problem , please check it now !

Thank You !

**Comment by mdazfar2** [comment]
@zalabhavy see what you have done.

<br>

image

**Comment by zalabhavy** [comment]
@mdazfar2 In localhost i am not able to login and not able to see any post so i use online complier to make this button can you tell me how to solve that ?
I need to connect with mongodb ?

image

image

**Comment by mdazfar2** [comment]
This PR is done by random PR

**Pull request closed without merging**
