### PR TITLE
Added hovering effect for Top contributors

### LINKED ISSUE #446: Feat: Add hovering effect for top contributors profile circles
### Describe the feature

Wanted to add hovering effect for the below profile circles

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #446 

## Description

- Added hovering effect for top contributors' profile circle for both `lightmode` & `darkmode`

- **Minor fix:** Fixed the text color for `contributor` in `darkmode`

## Video

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/00de352a-0edb-4414-a658-6d37175b5fdf

@mdazfar2 please review and merge this PR

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Asymtode712 Please update your sync fork

**Comment by Asymtode712** [comment]
@mdazfar2 Done

**Comment by mdazfar2** [comment]
@Asymtode712 I think there is delay of hover effect

**Comment by Asymtode712** [comment]
@mdazfar2, followings are the changes made:

- Added layering so that the hover effect works fine in the profile circle
- Changed `target="_blank` to  `target="_self` so that the redirection occurs in the active tab instead of opening in a new tab


https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/4474350d-bbd6-4d02-8d68-5058ffc56745

**Review by mdazfar2 — APPROVED** [review]

**Pull request merged**
