### PR TITLE
Feedback image

### LINKED ISSUE #173: Low quality Image
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Apurv7777**
Fixed #173

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Apurv7777 share screenshot

**Comment by Apurv7777** [comment]
image

**Comment by mdazfar2** [comment]
@Apurv7777 If it matched the color of the website tutle, it would have looked user friendly.

**Comment by Apurv7777** [comment]
image

**Pull request merged**
