### PR TITLE
Dark mode

### LINKED ISSUE #175: Dark Mode Issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Apurv7777**
### Added : from any page , you can toggle the dark mode.

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Apurv7777 leave this issue; someone other will work on this issue;

<br>

### It's not looks good to me

image

**Comment by Apurv7777** [comment]
I request you to merge this and let other solve that issue. The primary code for toggling dark mode on all pages is working perfectly. @mdazfar2

**Comment by Apurv7777** [comment]
There would be no one that satisfy's you completely. The project never ends fixing. Some changes are resolved here. Some changes would be resolved in next PR's by me. I guaranteed you. But, firstly , start building dark mode atleast. @mdazfar2

**Comment by mdazfar2** [comment]
> There would be no one that satisfy's you completely. The project never ends fixing. Some changes are resolved here. Some changes would be resolved in next PR's by me. I guaranteed you. But, firstly , start building dark mode atleast. @mdazfar2

<br>

@Apurv7777 Please don't think wrong you are a part of our team, I will discuss with someone and let you know

**Pull request closed without merging**
