### PR TITLE
feat: loader added

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
issue #404 solved

https://github.com/mdazfar2/HelpOps-Hub/assets/125277258/b72a410a-9957-4154-9d64-62f705e04507

### CODE REVIEW

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal It would be nice if it opens like a door after completion of loading.
- And it is taking a lot of time to load. Try to give only one round, meaning after one complete round, it should show the landing page.
- add this loading effect in all pages except `Resources page`.

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 review the PR

**Review by mdazfar2 — COMMENTED** [review]
@RamakrushnaBiswal That's great 🤩

**Comment by mdazfar2** [comment]
@RamakrushnaBiswal can you add effect on footer social icons as it is-

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/d559e871-828f-4560-85df-15fa71ea2c4d

**Comment by RamakrushnaBiswal** [comment]
Yes @mdazfar2

**Pull request merged**
