### PR TITLE
Feat: Want to make skeleteon For Dark mode #994

### LINKED ISSUE #994: Feat: Want to make skeleteon For Dark mode
### Describe the feature

there is skeleton which are looking odd in dark mode i want to fix 

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by nishant0708**
closes #994 

https://github.com/user-attachments/assets/2b33cf76-97db-4238-8cee-9b948196fb07

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @mdazfar2 please review it whenever possible

**Comment by mdazfar2** [comment]
@nishant0708 update sync fork

**Comment by nishant0708** [comment]
hey @mdazfar2 its synced already

**Comment by mdazfar2** [comment]
@nishant0708 Heads up that we might encounter errors during deployment of your changes.

<br>

image

**Comment by nishant0708** [comment]
> @nishant0708 Heads up that we might encounter errors during deployment of your changes.
> 
> 
> image

Umm is it because I am using local storage?

**Comment by nishant0708** [comment]
hey @mdazfar2 please check it now

**Comment by mdazfar2** [comment]
@nishant0708 please update sync fork once and let me know that you synced.

**Comment by nishant0708** [comment]
hey @mdazfar2  done

**Pull request merged**
