### PR TITLE
fix alignment of devops arsenal

### LINKED ISSUE #547: BUG: improper alignment of devops arsenel .
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

alignment of devops arsenal .
there is extra "H" also in helpops .
341509924-cf27be0a-3307-41dd-8db3-cb7ea4edf2c9

 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixed #547 

fixed the alignment of dev ops arsenal and also removed extra h   helpopshub .

.Screenshot 2024-06-21 001220

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 please review it once and merge my pull request under gssoc label .

**Comment by mdazfar2** [comment]
@ANKeshri make it size bigger and try to update the more description about your change 

<br>

image

**Comment by ANKeshri** [comment]
> @ANKeshri make it size bigger and try to update the more description about your changes
> 
> 
> image
image
is it fine now

**Comment by mdazfar2** [comment]
@ANKeshri create pr

**Comment by ANKeshri** [comment]
> @ANKeshri create pr

Should i create new pr , I have committed in this pr only .

**Comment by mdazfar2** [comment]
Close this PR and create new one @ANKeshri

**Comment by ANKeshri** [comment]
> Close this PR and create new one @ANKeshri

ok

**Pull request closed without merging**
