### PR TITLE
Fixed text color not properly visible in dark mode

### LINKED ISSUE #495: BUG: Text of some sections not properly visible in dark mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

Text of some sections is not properly visible in dark mode.
Before:
image
image

After:
image

Name and other inputs should be white in dark mode for proper visibility

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
Fixes #495 
I fixed text color not properly visible in dark mode.

Before :
image
image

After:
image

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/6b0d06a6-3787-4a40-a68f-1e20c7c89976

### CODE REVIEW

**Comment by Maana-Ajmera** [comment]
@mdazfar2 Please review my PR and merge it under gssoc. Thank you!

**Comment by mdazfar2** [comment]
@Maana-Ajmera Update your sync fork

**Comment by Maana-Ajmera** [comment]
@mdazfar2 okay sir doing it

**Review by mdazfar2 — APPROVED** [review]
Great work @Maana-Ajmera

**Comment by Maana-Ajmera** [comment]
> Great work @Maana-Ajmera

Thank you @mdazfar2 sir !

**Comment by mdazfar2** [comment]
@Maana-Ajmera please don't forget to follow us on [linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Pull request merged**
