### PR TITLE
Added Feedback Form Functionality

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added the functionality for email through feedback form .
closes : #222 

Hii if you are going to merge so please give level 3 because you know i also created contact us page whole new page with css but now it becomes of no use .

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  i raised the pr

**Comment by mdazfar2** [comment]
> @mdazfar2  i raised the pr
> 

I am a little busy, I will check and let you know @Ayushmaanagarwal1211 !

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 please check i am submitting a feedback form. If the feedback reached you please share the ss

**Comment by mdazfar2** [comment]
> @Ayushmaanagarwal1211 please check i am submitting a feedback form. If the feedback reached you please share the ss


and please resolve the conflict and update the sync fork and then pull and then push and create pr

**Comment by Ayushmaanagarwal1211** [comment]
Yes if I am correct you entered 
Email : founder@gmail.com
Message : hello is this working
Rating 2

**Comment by Ayushmaanagarwal1211** [comment]
Screenshot_2024-06-06-18-14-51-68_e307a3f9df9f380ebaf106e1dc980bb6

**Comment by Ayushmaanagarwal1211** [comment]
Yes I am reaching my home in 30 min then I will resolve it

**Comment by mdazfar2** [comment]
> Yes I am reaching my home in 30 min then I will resolve it

okk @Ayushmaanagarwal1211 and I more favour i need from you please raise an issue for fully responsive of website except contribution page and i assign you, do it as soon as possible. It totally ruined of Responsiveness. Try to make full responsive of homepage because it is most important. you know

**Comment by mdazfar2** [comment]
> Ya sure I will raise issue

Thank you @Ayushmaanagarwal1211

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 what happened @Ayushmaanagarwal1211 ?

**Comment by Ayushmaanagarwal1211** [comment]
Yes i am solving the conflict some changes the feedback form code that;s why it is taking some time

**Comment by Ayushmaanagarwal1211** [comment]
I will raise pr as soon as it solves

**Pull request closed without merging**
