### PR TITLE
added scroll to top button

### LINKED ISSUE #242: BUG: Missing Scroll to top button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this out
there are no scroll to top button
image

we can add it in right bottom

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@mdazfar2 

BUG: Missing Scroll to top button #242

close #242

i added scroll to top button in right side cornor
image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@mdazfar2 

please check this and merge it

**Comment by mdazfar2** [comment]
@dhruv8433 Couldn't find

<br>

image

**Comment by dhruv8433** [comment]
@mdazfar2 

now check it's working

**Comment by mdazfar2** [comment]
## Look a new bug was found from your changes. @dhruv8433 

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/ce79f8be-f079-418f-a65c-c13a56a60f56

**Comment by dhruv8433** [comment]
@mdazfar2 

please check out files changed
i only add css for display scroll to top  and one button 
i don't even touch faqs fiile

it's node my code bug

image

image

you can clearly chech this or `file changed` tab

**Comment by dhruv8433** [comment]
check this,  i already solved feeback form in responsive in #229 
but it still not looking responsive in live web

image

**Comment by dhruv8433** [comment]
@mdazfar2 

please merge this so i can create new pr

**Comment by dhruv8433** [comment]
ok

**Comment by dhruv8433** [comment]
@mdazfar2 

please share me new issue 
i will do it

**Comment by mdazfar2** [comment]
I'll be continue from 10 pm okk

**Comment by dhruv8433** [comment]
@mdazfar2 


Ok no problem 
Kindly review it and merge it

**Comment by dhruv8433** [comment]
@mdazfar2 

i added footer with social media icons
image

if you need anythign else please inform me

**Comment by dhruv8433** [comment]
pull from upsteram and resolve all the conflicts now you can check it and tell me if you need any kind of changes

**Pull request closed without merging**
