### PR TITLE
Front page responsive

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have created the responsive front page for all devices 

closes : #324

@mdazfar2  please check if found any distortion in the device for any screen size please let me know 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/ef378803-ef52-46f3-9673-d9f1ac5e3309

### CODE REVIEW

**Comment by mdazfar2** [comment]
**@Ayushmaanagarwal1211 Try to make responsive with hamburger as shown in the below video it is just for example**

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/1fd29098-a8e1-4cc8-87f1-c18d4c6939b1

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/c747db74-eb10-4abd-8206-d65800347e3a

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2 i added the hamburger please check it

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211, please try to make it fully responsive and adjust the buttons accordingly. I noticed you left too many spaces while making it responsive. You need to reduce the button size and maintain proper gaps according to the phone screen. Hope you understand what I mean.

<br>

image

**Comment by Ayushmaanagarwal1211** [comment]
So for that i am thinking the for medium screen sizes i will place the sponsor button visible outside the hamburger and for mobile device i will place it under hamburger because in medium displays too much gap is left if only logo and hamburger is present

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 you can put the sponsor button and dark mode button outside of hamburg

**Comment by Ayushmaanagarwal1211** [comment]
Currently i am not able to see dark mode is it their or may be after update

**Comment by Ayushmaanagarwal1211** [comment]
> @Ayushmaanagarwal1211 you can put the sponsor button and dark mode button outside of hamburg
> 
> * and try to make logo a llittle smaller

Ok

**Comment by mdazfar2** [comment]
> Currently i am not able to see dark mode is it their or may be after update

<br>

@Ayushmaanagarwal1211 okk no issue

**Comment by Ayushmaanagarwal1211** [comment]
> > Currently i am not able to see dark mode is it their or may be after update
> 
> 
> @Ayushmaanagarwal1211 okk no issue

Ok for this time i am moving the sponsor button outside after dark mode update i will also place that outside

**Comment by mdazfar2** [comment]
> > > Currently i am not able to see dark mode is it their or may be after update
> > 
> > 
> > @Ayushmaanagarwal1211 okk no issue
> 
> Ok for this time i am moving the sponsor button outside after dark mode update i will also place that outside

<br>

@Ayushmaanagarwal1211 definitely

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Updated

**Comment by mdazfar2** [comment]
> @mdazfar2 Updated

<br>

@Ayushmaanagarwal1211 I don't see any difference

**Comment by Ayushmaanagarwal1211** [comment]
I am checking please wait

**Comment by mdazfar2** [comment]
> I am checking please wait

Yes

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  can you please check it again maybe their is some glitch i again comitted this

**Comment by mdazfar2** [comment]
Let me

**Comment by mdazfar2** [comment]
not updated @Ayushmaanagarwal1211 

<br>

image

<br>

- i think you have to sync the fork and then you have to pull and push again

**Comment by Ayushmaanagarwal1211** [comment]
Uploading bandicam 2024-06-09 23-17-17-057.mp4…

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/7c9b07f8-5514-4b37-9833-c45ac4550a7f

**Comment by Ayushmaanagarwal1211** [comment]
I've updated like that @mdazfar2  are you able to see sponsor button

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 It not looks good to me

**Comment by Ayushmaanagarwal1211** [comment]
DO i have to remove the sponsor button later

**Comment by Ayushmaanagarwal1211** [comment]
like for very  small screen size

**Comment by mdazfar2** [comment]
image

please do something which looks attractive and good

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  did you have any figma design or i am thinking that the dark mode is not updated yet when the dark mode is updated so i can place both sponsor button and dark mode button outside the hamburger menu

**Comment by mdazfar2** [comment]
> @mdazfar2 did you have any figma design or i am thinking that the dark mode is not updated yet when the dark mode is updated so i can place both sponsor button and dark mode button outside the hamburger menu

@Ayushmaanagarwal1211 wait i will give you some small design

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 

<br>

image

<br>

- can we do that like this! what is your opinion?

**Comment by Ayushmaanagarwal1211** [comment]
If we open the hamburger menu then the logo will push below the menu's  IMO it not looks good because logo have to be on the top

**Comment by mdazfar2** [comment]
Leave the hamburger in its place; it is good where it is. @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok so i will place the logo below hamburger and sponsor and star us button together

**Comment by mdazfar2** [comment]
> Ok so i will place the logo below hamburger and sponsor and star us button together

yes let's see how it looks like

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
![Screenshot 2024-06-09 233828](https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/ec4ec71e-a44f-4b6d-aca5-6caa5d2bd0
It is looking like this

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 Oops don't touch from one another

**Comment by Ayushmaanagarwal1211** [comment]
yeah i am decreasing the size

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 also try to decrease the size of HelpOps-Hub and at the bottom, give some space to all of them from the bottom to each other

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  please check

**Comment by mdazfar2** [comment]
Yes

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 

image


- try to complete this in 2 line of sentence

**Comment by Ayushmaanagarwal1211** [comment]
Ok i will reduce font size

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  updated

**Comment by mdazfar2** [comment]
Much better! butI think you turned the `get started` button a little too low @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok moving up

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  done

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 

<br>

image

- I hope you understand

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2 Updated

**Review by mdazfar2 — APPROVED** [review]
@Ayushmaanagarwal1211 You are awesome ✨🧑‍💻

**Comment by Ayushmaanagarwal1211** [comment]
Thank You much much

**Comment by Ayushmaanagarwal1211** [comment]
I already did contributors page responsive but i need to merge the navbar with it so it takes some time i will raise pr by 9 am in morning

**Pull request merged**
