### PR TITLE
Changed position of form and image 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have changed the position of form and image to slightly right side keeping in mind about responsiveness .

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  please check deployment is completed

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 I have designed a new website for HelpOps-Hub, our team is working on it. Will you please help us?



<br>
 
It is how homepage looks like

**Comment by Ayushmaanagarwal1211** [comment]
Sure

**Comment by mdazfar2** [comment]
> Sure

@Ayushmaanagarwal1211 please join [discord](https://discord.gg/UWTrRhqywt)

**Comment by Ayushmaanagarwal1211** [comment]
I already joined

**Review by mdazfar2 — COMMENTED** [review]
@Ayushmaanagarwal1211

**Comment by mdazfar2** [comment]
Message me on discord I can't find

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2   


https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/7e9bfcb2-db19-4f7a-a587-be480ca54f60


https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/6041331e-fd07-43cd-b271-da6bef87da49

**Pull request merged**
