### PR TITLE
Added Burger menu

### PR DESCRIPTION
**Pull request by dhruv8433**
@mdazfar2 

i added burger menu in all screens 
please check this and merge it

image

footer
image

menus 
image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@mdazfar2 

please merge this so i can work on another assigns

**Comment by mdazfar2** [comment]
@dhruv8433 will let you know about that

**Comment by dhruv8433** [comment]
@mdazfar2 

Please check this and inform me if you want any modification 

Please merge it

**Comment by mdazfar2** [comment]
@dhruv8433 Waao This is what I expected from you.

**Comment by dhruv8433** [comment]
@mdazfar2 

now everything sovled
image

also note that,
burger menu added too

https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/be48c254-e89c-4980-b5a0-b7084210d879

**Comment by dhruv8433** [comment]
@mdazfar2 

now everything working perfect and i resolve all errors too
kindly merge it

**Comment by mdazfar2** [comment]
@dhruv8433 let me check

**Comment by dhruv8433** [comment]
@mdazfar2 

Ok

**Comment by dhruv8433** [comment]
Hey @mdazfar2 ,if you merged my pr then i try to logo design otherwise i do not do that also complaint in gssoc community

**Pull request closed without merging**
