### PR TITLE
when user click on particular faq only once open and also added close…

### LINKED ISSUE #225: BUG: FAQ's Answer open two times and not have close arrow
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

@mdazfar2 

check this ,
image

try to open faqs answer in responsive 
there is no close arrow

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
… icon

@mdazfar2 
BUG: FAQ's Answer open two times and not have close arrow #225

close #225

please add `level 2` label

check this out,
- i added logic for open only once faqs card
- also added close arrow

https://github.com/mdazfar2/HelpOps-Hub/assets/114583978/76922c02-3662-4d6d-b45c-99db6d242edb

### CODE REVIEW

**Comment by mdazfar2** [comment]
@dhruv8433 could you please elaborate it more

**Comment by mdazfar2** [comment]
@dhruv8433 check it once it already worked on deployed link; fast and let me know

**Comment by dhruv8433** [comment]
@mdazfar2 

yaa, it working now but when i rais the issue it doesn't work
and i added some `transaction` animation on card open please check that

**Review by mdazfar2 — COMMENTED** [review]
@dhruv8433  I can't find and try to search other bugs there are so many glitches on my web seach and raise an issue.

- & don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by dhruv8433** [comment]
@mdazfar2 

i told you this 
when user open faqs card the arrow should be changed

image


but it still have open arrow

**Pull request closed without merging**
