### PR TITLE
Fixed color of cards

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
Fixed color of cards 
Maybe by doing responsive i delete any container that contains color so i have fixed it and did it as before by changing some html and css

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/49205cb1-f881-4d16-a3ee-2f5181dc1e32

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  please check i've fixed it

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 thank you

**Review by mdazfar2 — APPROVED** [review]

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  shall i start working on contact page ?

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 

- Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by Ayushmaanagarwal1211** [comment]
Sure i am joining in

**Pull request merged**
