### PR TITLE
Contribution file

### PR DESCRIPTION
**Pull request by Varsani2520**
i edit the view more btn

### CODE REVIEW

**Comment by Varsani2520** [comment]
Hey @mdazfar2 ,
i complete the line alignment 
image
as well as see more button and bottom to top button remove

**Comment by mdazfar2** [comment]
@Varsani2520 Oops i dont like this

image

**Comment by mdazfar2** [comment]
> hey @mdazfar2 ,this is not my code

@Varsani2520 I am giving you an example that you have to do it like this

**Comment by Varsani2520** [comment]
image

**Comment by Varsani2520** [comment]
@mdazfar2 ,see my align is match with contributor card

**Comment by Varsani2520** [comment]
so what you want exactly can you provided demo video @mdazfar2

**Comment by mdazfar2** [comment]
@Varsani2520 demo video for what?

**Comment by Varsani2520** [comment]
i dont understood

**Comment by mdazfar2** [comment]
I will try to explain it to you in some other way. @Varsani2520

**Comment by Varsani2520** [comment]
yes

**Comment by Varsani2520** [comment]
i wii wait

**Pull request merged**
