### PR TITLE
video css fixed in mobile view

### LINKED ISSUE #1155: Feat: fixing intro video size of about us page in mobile view
### Describe the feature

fixing height width of intro video 

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhairyagothi**
closes #1155 

image

fixed 
kindly merge it

### CODE REVIEW

**Comment by mdazfar2** [comment]
@dhairyagothi these texts are also not responsive please make responsive these two sections also

<br>

image

<br>

image

**Comment by dhairyagothi** [comment]
> @dhairyagothi these texts are also not responsive please make responsive these two sections also
> 
> 
> image
> 
> 
> image

okay

**Comment by mdazfar2** [comment]
Hey @dhairyagothi, why did you add this here? Can you please explain the use of this on the about page?

<br>

image

**Comment by dhairyagothi** [comment]
> Hey @dhairyagothi, why did you add this here? Can you please explain the use of this on the about page?
> 
> 
> image

i have not addded this i have done changes in tailwind only

**Comment by dhairyagothi** [comment]
i think its of previous website should i remove this folder ?

image

**Comment by mdazfar2** [comment]
@dhairyagothi, but this is your PR, so who else could add this? Only you are working on this issue. What you say doesn't make any sense.

**Comment by dhairyagothi** [comment]
Done @mdazfar2

**Comment by mdazfar2** [comment]
> i think its of previous website should i remove this folder ?
> 
> image

Ohw shit It is already removed did you update sync fork 🤦🏻‍♂️🤦🏻‍♂️

**Comment by dhairyagothi** [comment]
> > i think its of previous website should i remove this folder ?
> > image
> 
> Ohw shit It is already removed did you update sync fork 🤦🏻‍♂️🤦🏻‍♂️

ya updated now check all set

**Review by mdazfar2 — APPROVED** [review]

**Pull request merged**
