### PR TITLE
Fixed link to open source community 

### LINKED ISSUE #499: BUG: Link of Open source community not working and text not visible of new section added in dark mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

- Sorry for creating similar issue of text not visible in dark mode but since it is new section added , I observed it just now.
- Also Open source community is directing to contributors in the code but the page is not found so there may be some error in the path provided.

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/2d983d98-8715-40e7-a80e-5ee7985cb742

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Maana-Ajmera**
fixes #499 

Before:

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/1880b9d4-a001-4eab-a9a6-645f2eb147e4

After:

https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/83eb92ad-5bc4-4324-ab96-6437dc9e72ab

### CODE REVIEW

**Comment by Maana-Ajmera** [comment]
@mdazfar2 please review my PR and merge it under gssoc . If there is anything else I could work on , do let me know , I will be happy to work on it.

**Review by mdazfar2 — COMMENTED** [review]
@Maana-Ajmera Amazing Do the same thing for all pages.

**Comment by Maana-Ajmera** [comment]
@mdazfar2 sure..sorry I didnt notice that

**Comment by Maana-Ajmera** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/162733812/e5c2aeab-7e39-4a71-b26e-2c7b1671940f

done

**Comment by mdazfar2** [comment]
@Maana-Ajmera update sync fork

**Comment by Maana-Ajmera** [comment]
@mdazfar2 doing it

**Comment by Maana-Ajmera** [comment]
@mdazfar2 done

**Comment by mdazfar2** [comment]
@Maana-Ajmera I think you removed line from the link from some pages

image

**Comment by Maana-Ajmera** [comment]
> @Maana-Ajmera I think you removed line from the link from some pages
> 
> image

@mdazfar2 no sir, I have not removed it , it was not there in the code, should I add it ?

**Comment by mdazfar2** [comment]
Yes

**Comment by Maana-Ajmera** [comment]
> > @Maana-Ajmera I think you removed line from the link from some pages
> > image
> 
> @mdazfar2 no sir, I have not removed it , it was not there in the code, should I add it ? , you can check from the code I have changed..I didnt remove it

**Comment by Maana-Ajmera** [comment]
> Yes

@mdazfar2 ok

**Comment by Maana-Ajmera** [comment]
@mdazfar2 done

**Comment by Maana-Ajmera** [comment]
@mdazfar2 , links and line are now present in every page

**Comment by mdazfar2** [comment]
@Maana-Ajmera I'll see after some time as my laptop isn't with me right now.

**Comment by Maana-Ajmera** [comment]
> @Maana-Ajmera I'll see after some time as my laptop isn't with me right now.

@mdazfar2 Thank you .. and sorry for my mistakes, I should have observed them earlier.

**Comment by mdazfar2** [comment]
@Maana-Ajmera It's okay, everyone makes these small mistakes. It happens to me too. By the way, you are a good developer.

**Review by mdazfar2 — APPROVED** [review]

**Comment by Maana-Ajmera** [comment]
> @Maana-Ajmera It's okay, everyone makes these small mistakes. It happens to me too. By the way, you are a good developer.

@mdazfar2 Thank you for your kind words...if there is anything else I could do , do let me know ... I am really enjoying working on this project.

**Comment by mdazfar2** [comment]
Sure @Maana-Ajmera

**Pull request merged**
