### PR TITLE
Feat: .hamburger close icon add 

### LINKED ISSUE #751: Feat: `.hamburger` close icon add
### Describe the feature

- In this project `mobile` site  `nav-item` open to click the `.hamburger` this is only open icon not added the close icon.
- If i want to implement the close icon.
- please assign me.

### Add ScreenShots

[Screencast from 2024-06-30 09-33-32.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/9c3c8b17-aee7-4a7b-bac2-12b23eb19707)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by sivaprasath2004**
Hello @mdazfar2 ,

closes #751 

- I will finish it... 
- please merge...

### Before

[Screencast from 2024-06-30 09-33-32.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/9c3c8b17-aee7-4a7b-bac2-12b23eb19707)

### After

[Screencast from 2024-07-01 19-07-06.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/5003671b-743d-4126-b5b5-4137df264ea7)

### CODE REVIEW

**Comment by mdazfar2** [comment]
hey @sivaprasath2004 great work but it looks different on mobile responsive 

<br>

image

**Comment by sivaprasath2004** [comment]
@mdazfar2, what is the  mobile size ?
I can check this is work properly

**Comment by sivaprasath2004** [comment]
@mdazfar2 Try this time,

**Comment by sivaprasath2004** [comment]
Screenshot from 2024-07-02 06-56-41

**Comment by mdazfar2** [comment]
@sivaprasath2004 update sync fork

**Comment by sivaprasath2004** [comment]
@mdazfar2  please merge it..

**Review by mdazfar2 — APPROVED** [review]
Thank you

**Pull request merged**
