### PR TITLE
Enhanced the Front Page 

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have Enhanced the frontpage by giving equal spacing , fixed alignment of all items ,
And created the almost similar design

closes : #505 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/76409df2-859f-48c0-88bc-39898cef8c33

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
@Ayushmaanagarwal1211 great work

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir i am not understanding how just enhanced word make the work same

**Comment by Ayushmaanagarwal1211** [comment]
Here i Changed the front page i have added a video and theme is completely different thing from that

**Comment by Ayushmaanagarwal1211** [comment]
In theme i was talking about the whole website changing to new theme

**Comment by Ayushmaanagarwal1211** [comment]
Sir this is not fair with me i am giving most of my time and my points getting reduced by just one word sir i know i am not doing anything wrong creating such things take much time i am giving my proper time and after sometime my points are getting reduces

**Comment by sanjay-kv** [comment]
https://github.com/GSSoC24/Contributor/discussions/517

refere to this section i have highlighted the issue here. 
image


made it public , because I'm 100 % people are preparing to point out your PR by end of the program

**Comment by Ayushmaanagarwal1211** [comment]
Ok sir i am sending message their

**Comment by sanjay-kv** [comment]
image
image
image
image

image

image

200 points+ for darkmode
 and 200+ responsiveness. 

We have mentioned multiple times if work on responsive work do it for entire website and get 45 points if any bugs level 1 or level 2 can be awarded again on new PR not like 6 pr to fix the bugs 
Look at this

**Comment by Ayushmaanagarwal1211** [comment]
Sir but website is changing day by day when i do it first responsive then it doesn't contains blogs section and forum section so how can i make it responsive 
Sir we develop the website so we need to add many components so how can i know that what will i include in future and make it responsive

**Comment by mdazfar2** [comment]
@sanjay-kv sir,

I understand the guidelines, but as a project admin, we are creating pages one by one. A few days ago, we created a page for the DevOps forum, then we made it responsive and added dark mode. After that, we created a backend design for the DevOps forum and implemented it, then we made it responsive and added dark mode again in other issue and PR. As we add pages, we are gradually implementing responsiveness and dark mode. There is no scam; Ayushmaan is working genuinely as I have seen.

**Comment by sanjay-kv** [comment]
I understand their website is changing, 
so gave 3 level2 for making a webpage responsive. 

anything beyond that is hard to award. 
@mdazfar2 
image
there is no mention on such things in comments, as a reviewer its hard to look into the code section of 200 PR. 

If a proper comment section has been followed it 
such as dark mode for devops forum. 
dark mode for other forum.

**Comment by Ayushmaanagarwal1211** [comment]
Sir so please revert my level back and give me time of one day i will add all title and description for everything properly

**Comment by sanjay-kv** [comment]
also adding those comments wont help i guess.

image

look at this level 3 for adding just dark mode. i don't think its fair to other contributors.

**Comment by sanjay-kv** [comment]
I will also check this with technical team. 
meanwhile you can change the commits comments

**Comment by Ayushmaanagarwal1211** [comment]
> also adding those comments wont help i guess.
> 
> image
> 
> look at this level 3 for adding just dark mode. i don't think its fair to other contributors.

Sir for the tags pr i have created the whole tag page from the scratch their is nothing before like tag in the whole website i just not make it responsive sir but i created the whole new component , Created it responsive adn added dark mode to it

**Comment by Ayushmaanagarwal1211** [comment]
Sir and their are many things i have did minumum 3 things in each pr i didn't just make it responsive

**Comment by Ayushmaanagarwal1211** [comment]
> Sir and their are many things i have did minumum 2 things in each pr i didn't just make it responsive

**Comment by Ayushmaanagarwal1211** [comment]
> I will also check this with technical team. meanwhile you can change the commits comments

Ok sir i will add proper Note for reviewers to all my pr's

**Comment by sanjay-kv** [comment]
I will check with Tech team if they find its reasonable will revert back, anyhow this changes wont affect you drastically.

**Comment by Ayushmaanagarwal1211** [comment]
Sir i thing where peoples are getting level 2 just for enhancing so creating the whole new UI is capable of getting level 3

**Comment by Ayushmaanagarwal1211** [comment]
> I will check with Tech team if they find its reasonable will revert back, anyhow this changes wont affect you drastically.

Ok sir

**Comment by sanjay-kv** [comment]
The question is how many UI for single repo, 3 is reasonable UI complete change beyond that its fishy. 

I should have limited this repo max technical contribution to 1500. Now its too late.

**Comment by mdazfar2** [comment]
@sanjay-kv sir

Please look at the screenshot below with red highlight square box. I have added that Aayushmaan also described the work with dark mode. Dark mode is just a small part of the significant work he has done, like backend integration, functionality of followers and following, and many other things. Please don't focus on the text "Dark mode." He has completed only a few PRs for dark mode and received only level 1. Please look at the description as well.

<br>

image

**Comment by sanjay-kv** [comment]
+ Im started reviewing from top 1, top 50 as these people are getting some goodies and stuff and major influence on the leaderboard.
So we are not comparing other people when we talk about the changes on the particular contribution. 
We will talk in terms of guideline provided as all the others contributors will also go through same thing shortly

**Comment by Ayushmaanagarwal1211** [comment]
sir https://www.helpopshub.com/  
This is the website link and you can self check the pages their is nohing fishy all the pages are related to each other

**Comment by sanjay-kv** [comment]
> sir https://www.helpopshub.com/ This is the website link and you can self check the pages their is nothing wrong all the pages are related to each other And the changes i did are all in the working state

UI is good though

**Comment by Ayushmaanagarwal1211** [comment]
> > sir https://www.helpopshub.com/ This is the website link and you can self check the pages their is nothing wrong all the pages are related to each other And the changes i did are all in the working state
> 
> UI is good though

Yes sir you can check it with your technical team if they found anything same in the code or repeated work i have no problem with that but if my all code are different and they have valid working so please revert it back because you know i am on the top and giving my whole day just to open source and then reducing points with doing anything wrong it will demote the motivation sir 
Hope You Understand

**Comment by sanjay-kv** [comment]
> @sanjay-kv sir
> 
> Please look at the screenshot below with red highlight square box. I have added that Aayushmaan also described the work with dark mode. Dark mode is just a small part of the significant work he has done, like backend integration, functionality of followers and following, and many other things. Please don't focus on the text "Dark mode." He has completed only a few PRs for dark mode and received only level 1. Please look at the description as well.
> 
> 
> image

thats a small area 
image
image
image
image

What im telling is the process you follow is completely wrong, we never do this in real time project,

You create a figma page with help of UI designer, finish the entire work on the webpage, get it approved. 
Then the developer will work on on go. 
and award them 45 points or max 90 points on the entire developments including bug fix or something. 
This seems so absurd to me atleast from my experience of SDE for 3+ years.

From PM and other contributor perspective we see the commits and change and we feel like its not a fair contribution.

**Comment by Ayushmaanagarwal1211** [comment]
> The question is how many UI for single repo, 3 is reasonable UI complete change beyond that its fishy.
> 
> I should have limited this repo max technical contribution to 1500. Now its too late.

Sir but this repo is open for all everyone can come here and contribute in this their is not only me i am contributing and i am not stopping any one to contribute sir 
So sir why my points are reducing if i am doing the correct work

**Comment by Ayushmaanagarwal1211** [comment]
Sir you can share all my pr to the testing team if they say that i did same work then please down else it will not fair with me sir

**Comment by sanjay-kv** [comment]
[review.pdf](https://github.com/user-attachments/files/16398823/review.pdf)

Here is list of PR

**Comment by mdazfar2** [comment]
@sanjay-kv, Sir, we already have a Figma design and a Canva mockup for the website. I'll share the links for your reference. As you mentioned, the current design lacks responsiveness and dark mode functionality.

- figma design here --> [figma](https://www.figma.com/design/eqORN85KL4gsh5qxqNMVFx/Helpops-hub?node-id=0-1&t=83vsJueRfKn9ZmSz-0)

- canva design here --> [canva](https://www.canva.com/design/DAGJgQDVy6c/7fJEYqMycuZ2uFOi1zatJA/edit)

- additional thing for mobile app --> [mobile figma](https://www.figma.com/design/iNM18Yj9XI0RIlgIk9Dwgy/HelpOps-Hub---Mob-App?t=XLMnpEdrO1g3w8us-0)

***Than you***

**Comment by sanjay-kv** [comment]
> > The question is how many UI for single repo, 3 is reasonable UI complete change beyond that its fishy.
> > I should have limited this repo max technical contribution to 1500. Now its too late.
> 
> Sir but this repo is open for all everyone can come here and contribute in this their is not only me i am contributing and i am not stopping any one to contribute sir So sir why my points are reducing if i am doing the correct work

image
I hope you read the guidelines. 
https://github.com/GSSoC24/Contributor/tree/main/gssoc-guidelines
image

**Comment by mdazfar2** [comment]
@sanjay-kv, Sir, the screenshot you shared doesn't seem to be related to my repository. I'm not familiar with "Ansh." I believe you might have sent the wrong screenshot by mistake.

**Comment by sanjay-kv** [comment]
> @sanjay-kv, Sir, the screenshot you shared doesn't seem to be related to my repository. I'm not familiar with "Ansh." I believe you might have sent the wrong screenshot by mistake.

That's the screenshot from guidelines .

**Comment by Ayushmaanagarwal1211** [comment]
Yes sir I read that but if I am correct then 
150 points max for adding documentation , pr projects
And below that it has written that their is no limit for contributing any technical functionality

**Comment by mdazfar2** [comment]
> > @sanjay-kv, Sir, the screenshot you shared doesn't seem to be related to my repository. I'm not familiar with "Ansh." I believe you might have sent the wrong screenshot by mistake.
> 
> That's the screenshot from guidelines .

@sanjay-kv, Okay, sir! I've familiarized myself with the guidelines since starting the program. I apologize if any mistakes were made on my part. I believe in recognizing hard work and effort. When speaking with contributors on Discord, I can gauge their dedication. If resolving an issue takes significant time, I'll consider assigning a level 3. Please review our design below.

- figma design here --> [figma](https://www.figma.com/design/eqORN85KL4gsh5qxqNMVFx/Helpops-hub?node-id=0-1&t=83vsJueRfKn9ZmSz-0)

- canva design here --> [canva](https://www.canva.com/design/DAGJgQDVy6c/7fJEYqMycuZ2uFOi1zatJA/edit)

- additional thing for mobile app --> [mobile figma](https://www.figma.com/design/iNM18Yj9XI0RIlgIk9Dwgy/HelpOps-Hub---Mob-App?t=XLMnpEdrO1g3w8us-0)

***Than you***

**Comment by sanjay-kv** [comment]
> Yes sir I read that but if I am correct then 150 points max for adding documentation , pr projects And below that it has written that their is no limit for contributing any technical functionality

correct 
+ there is one more thing. 
image

your responsive PR thing come under it.

**Comment by sanjay-kv** [comment]
> > > @sanjay-kv, Sir, the screenshot you shared doesn't seem to be related to my repository. I'm not familiar with "Ansh." I believe you might have sent the wrong screenshot by mistake.
> > 
> > 
> > That's the screenshot from guidelines .
> 
> @sanjay-kv, Okay, sir! I've familiarized myself with the guidelines since starting the program. I apologize if any mistakes were made on my part. I believe in recognizing hard work and effort. When speaking with contributors on Discord, I can gauge their dedication. If resolving an issue takes significant time, I'll consider assigning a level 3 and nothing else. hope you review our design below. ):
> 
> * figma design here --> [figma](https://www.figma.com/design/eqORN85KL4gsh5qxqNMVFx/Helpops-hub?node-id=0-1&t=83vsJueRfKn9ZmSz-0)
> * canva design here --> [canva](https://www.canva.com/design/DAGJgQDVy6c/7fJEYqMycuZ2uFOi1zatJA/edit)
> * additional thing for mobile app --> [mobile figma](https://www.figma.com/design/iNM18Yj9XI0RIlgIk9Dwgy/HelpOps-Hub---Mob-App?t=XLMnpEdrO1g3w8us-0)
> 
> _**Than you**_

this ain't mean to you or your repo, its important this thing to be questioned and have a record of the conversation. 
I had question on review , we are sorting it down.

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir i don't want to increase this conversation but just please give me  5 min and read All this carefully 

## From the Contributors points of view the things we see that 
- Is the repo is online or offline so that did we get assigned by raising an issue 
- 2nd does the tech stack is the same as our tech stack 
- Does the repo owner Will reply to your queries and issues 
- And at last The scope of raising more issues on the repi

So 2 months before i raised one issue and got assigned and then connected on discord with the @mdazfar2 
Sir i don't think that their is any other reason for contribution

## From the Admin Point of view 
- He want their website should be the best and any thing or feature contributor wants to implement so their is no reason to not giving permission as they won't have to pay a single penny for that 


Sir and if We talk about that it creates discrimination with other so sir i want to clear one points 
- 
image
So see this image and this image 
image
 YOu can clearly see the difference between the number of issues 
I am not able to stop anyone from raising an issue they just want the points for just adding a project i.e is free anywhere at google they just got points by adding projects  so its depend on the contributor on which repo they want to work 
My All contributions are open for all . Everyone can see my contribution list so by seeing that list they can come and raise issues but they didn't even  do that that's not my fault sir 

And sir 
image
I clearly mentioned a note in the pr's i i created in these ten days 
I clearly mentioned that i just took approx 10 points for making it responsive i also mentioned 3 points Sir except that what the other thing should i do so that you can clearly understand the changes and sir as i know taking 10 points for responsiveness to completely different code is not under the guidelines .


Sir if i am giving my whole time and i  did contributions even at my exam time so it's my right to get the proper points for the time and effort i am giving 
So sir if you read all that you can clearly understand my points and the things left is i will update all my pr with this kind of noted and then please send it to technical team if they will found any duplicacy so then remove else please revert it back 

And sir we can also connect on a meet where i can explain you live and show the discussions about the project i did with afzar i will reply within 5 min sir by this you can understand the time i am giving to the GSSOC 

Thank You

**Comment by Ayushmaanagarwal1211** [comment]
So i hope sir you will take the decisions accordingly and will assure that nothing will unfair happen with deserving contributor

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir can you just give 5 min to read this 

> @sanjay-kv Sir i don't want to increase this conversation but just please give me 5 min and read All this carefully
> 
> ## From the Contributors points of view the things we see that
> * Is the repo is online or offline so that did we get assigned by raising an issue
> * 2nd does the tech stack is the same as our tech stack
> * Does the repo owner Will reply to your queries and issues
> * And at last The scope of raising more issues on the repi
> 
> So 2 months before i raised one issue and got assigned and then connected on discord with the @mdazfar2 Sir i don't think that their is any other reason for contribution
> 
> ## From the Admin Point of view
> * He want their website should be the best and any thing or feature contributor wants to implement so their is no reason to not giving permission as they won't have to pay a single penny for that
> 
> ## Sir and if We talk about that it creates discrimination with other so sir i want to clear one points
> image So see this image and this image image YOu can clearly see the difference between the number of issues I am not able to stop anyone from raising an issue they just want the points for just adding a project i.e is free anywhere at google they just got points by adding projects so its depend on the contributor on which repo they want to work My All contributions are open for all . Everyone can see my contribution list so by seeing that list they can come and raise issues but they didn't even do that that's not my fault sir
> 
> And sir image I clearly mentioned a note in the pr's i i created in these ten days I clearly mentioned that i just took approx 10 points for making it responsive i also mentioned 3 points Sir except that what the other thing should i do so that you can clearly understand the changes and sir as ithink that taking 10 points for responsiveness to completely different code completely lies under the guidelines
> 
> Sir if i am giving my whole time and i did contributions even at my exam time so it's my right to get the proper points for the time and effort i am giving So sir if you read all that you can clearly understand my points and the things left is i will update all my pr with this kind of noted and then please send it to technical team if they will found any duplicacy so then remove else please revert it back
> 
> And sir we can also connect on a meet where i can explain you live and show the discussions about the project i did with afzar i will reply within 5 min sir by this you can understand the time i am giving to the GSSOC
> 
> Sir i don't know why are you just judging my whole pr just on the basis of one similar word in the pr it's just the extra thing i am doing please read the full title and description and then if you find duplicacy then remove points Thank You

**Comment by sanjay-kv** [comment]
These are the technical team comments only for the flagged "responsive" and "dark mode" PR

Your contributions are good, but doing multiple contributions is mostly enhancement and carry on work from the existing enhancement made. so we can provide max level 1 or level 2 (if code change and implementation are high) for this. 

Lets take one example: The below repo you have rewarded level 3. Codebase first of all doesn't worth enough. 
```
https://github.com/mdazfar2/HelpOps-Hub/pull/261
```
this page responsive is mentioned in pr 150. (https://github.com/mdazfar2/HelpOps-Hub/pull/150) you already got level 3 to it. 
Even considering Admin change the UI, the max you can get it level1, as you are not even creating anything from scratch . Its just some changes to the existing file. Level 3 again is not at all worth it and not fair .

The below are some of the comment from technical team of 4

https://github.com/mdazfar2/HelpOps-Hub/pull/150
```
level3 is ok for clarification it is not creating complete website. It is making the website responsive. level3 is because it changes multiple pages responsive.

```
https://github.com/mdazfar2/HelpOps-Hub/pull/164
```
this page responsive is mentioned in pr 150. why because you said making the website responsive and got level3.

```
https://github.com/mdazfar2/HelpOps-Hub/pull/261
```
this page responsive is mentioned in pr 150. why because you said making the website responsive and got level3.


```
https://github.com/mdazfar2/HelpOps-Hub/pull/327
```
this is just clone of official website with website 2.0 already taken the level3 for website responsive

```
https://github.com/mdazfar2/HelpOps-Hub/pull/376
```
this is just clone of official website with website 2.0 already taken the level3 for website responsive

```
https://github.com/mdazfar2/HelpOps-Hub/pull/941
```
this is just clone of official website with website 2.0 already taken the level3 for website responsive

```
https://github.com/mdazfar2/HelpOps-Hub/pull/944
```
this is just clone of official website with website 2.0 already taken the level3 for website responsive

```
https://github.com/mdazfar2/HelpOps-Hub/pull/974
```
in this few are from pr 944. 



```
https://github.com/mdazfar2/HelpOps-Hub/pull/979
```
these to are almost same can give level3 to any one of these.
```
https://github.com/mdazfar2/HelpOps-Hub/pull/991
```

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1007
```
can give level2 for this

```
https://github.com/mdazfar2/HelpOps-Hub/pull/941
```
if level removed here than give level3 for pr 1007 why because both done by him and used tailwind for responsive it make simple as it is utility first framework

```
https://github.com/mdazfar2/HelpOps-Hub/pull/974
``` 
level1 one is ok because this page ui and functionality and responsive is done by him. not need to mention those changes with here.

```
https://github.com/mdazfar2/HelpOps-Hub/pull/979
```
this also done by him in some previous prs. again no need to mention your previous prs.

```
https://github.com/mdazfar2/HelpOps-Hub/pull/991
```
repeated 

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1007
```
can give level3

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1122
```
can give level1 

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1156
```
level1 is ok

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1170
```
no need of any level

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1187
```
level1 is enough.

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1172
```
can give level2

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1195
```
level2 ok

```
https://github.com/mdazfar2/HelpOps-Hub/pull/1206
```
can give level1 


these are from the other repos
```
https://github.com/Counselllor/Counsellor-Web/pull/992
``` 
level3 for only responsive -> need to reduce

```
https://github.com/Counselllor/Counsellor-Web/pull/1021
```
level3 for responsive form -> may need to level2

```
https://github.com/Counselllor/Counsellor-Web/pull/1040
``` 
level3 reasonable because complete page, responsive and dark mode.

```
https://github.com/Counselllor/Counsellor-Web/pull/1270
```
level2 not reasonable because it is not creating it is making this page responsive only. 

```

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Ok sir i am satisfied with many comments but not with all like i am mentioning these i created UI from scratch and added many things with these  not just do it responsive i have written all that in the title and i think where user are getting level 2 for enhancing so it should get level 3 for creating the whole UI 


## Sir the main thing i want to say that i have added responsive in the title like with the creation of whole new UI sir the NEW UI is important i have completed all things in one pr that's why if i first create the UI and then Raise another for responsive and dark mode then sir i can understand that this will be wrong but i have completed the whole new structure 

Like in #1007 
image
Sir here is the image i have created the whole new ui from scratch and also added responsive and dark mode so i completed all that in sinlge pr so IMO level 3 is worth it for creating the whole new UI and attching with the code 
image

in #1122 
I created whole new UI of tags page their is nothing like tags before so i created it from scratch 
image
image

sir in pr #1170 
Again i created a new ui i just written responsive and dark mode because i completed the whole ui in just one pr 

image
sir in this and in above pr's i cerated a whole new component that doesn't needs in only responsive 

sir in #1172 
I Integrated whole UI with backend and make it completely functional sir as creation of the whole dashboard from the scratch can even take 70 points 3 points for its creation and level 2 for its backend integration to fetch real time updates

sir in #979 and #974 
In 979 i created the whole new UI for the followers page that is completed with responsive and dark mode from scratch and then in the new one i integrated the whole backend with it i think sir in combine 50 points are worth it 

sir in #259 i have integrated the working through email js not ui
image


sir in #1097
I have added a completely new tooltip using new library and fix the image is not showing atleast lvl2 is worth it you can ignore responsive 

#906 
sir i implemented the whole dark mode for these new sections and  i didn't get 200+ more points for dark mode 


#902 
sir here again if you ignore responsive i added the dashed border it must get lvl1 

#889 
sir here i have added dark mode to all pages i didn't raised any pr like that so even this is capable of getting lvl 2 it contains 5-6 pages 

sir in #136 
Again i created whole new FAQ page and got only lvl 1 

and sir #119 
again i created a whole new page but lvl 2 is not bad i am satisfied with that 

https://github.com/MAVRICK-1/e-commerce_website/pull/379

sir again in this pr i improved the seo by improving the performance then why it got lvl 1 


## sir you can directly send it to testing team they can easily understand what i am trying to say

**Comment by Ayushmaanagarwal1211** [comment]
Sir and if creation of new component is not worth it for lvl 3 so i know many pr's of other contributor  i can mention all that 
I hope you will also review that

**Comment by Ayushmaanagarwal1211** [comment]
Sir i understand your concern about responsive but in many pr's i just added it as a part the main thing is different 
Sir as you previously said that if i am creating a component so i should create the complete component so that's why i just added responsive and dark mode 

## See the components i have created is complete i doesn't left anything in that and also created from scratch the only concern of my is this only

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv sir and also for codar hub repo 

https://github.com/user-attachments/assets/e95587bd-5951-4f40-b1ad-4f595bf8f41a

SEE on the original leaderboard only 40 points are counted but in your's it is showing more that 150

**Comment by Ayushmaanagarwal1211** [comment]
## Sir as In all the pr's i have mentioned are completely different from each other 

Sir  after this much explanation my points still deducted by giving responsive as a reason so sir this gonna be completely unfair with me 

And sir i don't know whether you did review of all the pr's of Presently No.1 Contributor But i just want to highlight some things there 

image

image
image
image

Sir in the gamezone and metaverse he got level 3 for each pr's and you know very well all these games are freely available anywhere on the google and just by copy pasting he got level 3 you know that no one writes the code of 26 files long just for lvl3  it must reduced to lvl 1 or remove the lvl as if my work on completely new file will b counted as Redundant 

But still the points of him is not deducted 
image
here this guy just took complete 150 points for doing the same thing

image

Sir here you can even see that level 3 for writing articles know sir you can easily understand like what the impression will these pr's leave for the new comer when he see that the top player got 1000+ points just by doing this documentation work 
You can compare my documentation work with his work then you got the clear result who did the most technical and fair work 


Sir after doing such a harsh inspection of all my pr's you should do the same for top 1 as well

Sir i don't think that their is a place of any documentation work for the  actual winner in the open source program it's mainly depend on the technical work 

I am ready for you can remove all documentation points from my pr as well as from his pr this will give you the actual and the fair winner 
Their is only 3 days left for that i think after all that you clearly understood my points 

And sir their is many many pr related to only documentation and on the counsellor hub repo that are related to dark mode and responsive but i didn't mentioned all that 

so please give proper time and review those pr's

**Comment by sanjay-kv** [comment]
mate i started review from you, i will proceed to them going forward. 
If you are ready to understand the changes only I can go ahead to do the similar changes to their PR by highlighting you already gone through point reduction. 

else when I change labels people points to other people PR. 

and this is time consuming process. nishant is yet to go through it, I spoke to him saying internal team has done analysis found spam on duplicate issue,he is fine with it. i will do his review tomorrow

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv Sir i am satisfied with your decision but sir i am having concern with these 5 pr's as according to your testing team the creation of whole new UI should get lvl 3 but sir please just one time read the complete title just ignore responsive and dark mode 
I have created a whole complete new component from the scratch sir in these pr's 
- #1007 
- #1122 
- #1170 
- #136 
- #1097 

sir please see in 1007 i created complete create post UI from scratch responsive doesn't matter here i just added because i created completely 
sir in 1122 i created whole new Tags UI from scratch 
In #1170 i created whole new Dashboard 
sir in #1097  i added new tooltip and image placeholder sir you can remove responsiveness
and sir last is #136  i created a complete new FAQ page sir 

Sir my concern is related to only these pr's sir all these pr's are seeing as just responsive but sir responsiveness is just the extra thing i have added please look closely 
Sir this is completely different issue i am just trying to say this and need my deducted points on that pr's only

**Comment by Ayushmaanagarwal1211** [comment]
and sir @sanjay-kv  i saw this today that i created the issue first for filtering the blogs but project admin assigns him and merged that pr and closed that pr 
Sir i have sended many message but he is online but not replying on a single message

**Pull request merged**
