### PR TITLE
added Toastify message

### PR DESCRIPTION
**Pull request by anagha-chaudhari**
Fixes issue #573 

Toastified message is added. 
Please review the PR and if any changes are needed, I will make them accordingly

https://github.com/mdazfar2/HelpOps-Hub/assets/143149376/2dc17a91-6c74-4a24-a894-100891e6523d

### CODE REVIEW

**Comment by anagha-chaudhari** [comment]
@mdazfar2 kindly review the pr

**Comment by mdazfar2** [comment]
Hey @anagha-chaudhari it is well but the validation is not working properly

**Comment by anagha-chaudhari** [comment]
Hi @mdazfar2 ,
So are you saying that it should check whether all details are completely filled before submitting and display a message if the details are incomplete or rating isn't given?

**Comment by anagha-chaudhari** [comment]
Can you clarify so I may work on it

**Comment by mdazfar2** [comment]
@anagha-chaudhari When users submit their form, it will automatically clear after 2 to 3 seconds. I hope you understand.

**Comment by anagha-chaudhari** [comment]
Okay, I get it

**Comment by anagha-chaudhari** [comment]
Here @mdazfar2 , now the form clears itself after submitting. Please review

https://github.com/mdazfar2/HelpOps-Hub/assets/143149376/f71d4380-15c1-43ae-90c4-e4ceafd58d6b

**Comment by mdazfar2** [comment]
@anagha-chaudhari Great, I will review it by morning.

**Comment by anagha-chaudhari** [comment]
@mdazfar2 Yes, I have synced the fork now

**Review by mdazfar2 — APPROVED** [review]
Lgtm

**Comment by anagha-chaudhari** [comment]
Thank you @mdazfar2

**Comment by mdazfar2** [comment]
@anagha-chaudhari - Don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Pull request merged**
