### PR TITLE
Add - Dockerize Spring-boot with Github-Actions

### LINKED ISSUE #1106: Topic: Automating Dockerization of Springboot application with GitHub actions
### Describe the types of DevOps topics you'd add in HelpOps-Hub Resource pages

I am going to build the application, create a Docker image, and push it to a Docker registry (like Docker Hub). I will automate these entire process using GitHub actions for ensure that every code change triggers a consistent build and deployment process.

### How many and what types of DevOps tools are you adding?

Docker, Docker hub, GitHub actions, Spring boot

### How many years of experience do you have in the DevOps field?

2 months

### Could you share some screenshots or a video of your previous DevOps work?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [ ] I'm DevOps professional
- [X] Soon, I'll complete it and create a Pull Request.
- [X] I'm a beginner in DevOps, but I'll try to contribute the best resources with hands-on experience.

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
This pr fixes #1106

### CODE REVIEW

**Comment by mdazfar2** [comment]
@DharshiBalasubramaniyam It all shows that you copied and pasted from someone else, and the screenshot is not visible. Sorry, but I have to close your PR. Please don't be discouraged.

**Comment by DharshiBalasubramaniyam** [comment]
> @DharshiBalasubramaniyam It all shows that you copied and pasted from someone else, and the screenshot is not visible. Sorry, but I have to close your PR. Please don't be discouraged.

@mdazfar2 What copy paste? These are my own notes. I have learned docker last month.

I myself done all of these in practical manner.

Below is my practical repository 

https://github.com/DharshiBalasubramaniyam/Springboot-CI-CD-Pipeline

After learning any new technology usually I write blog articles to share my experience.

Below is my latest blog article regarding this topic.

https://medium.com/@dharshib.8/demystifying-docker-for-spring-boot-automation-with-github-actions-716652668d7e

**Comment by mdazfar2** [comment]
Okay @DharshiBalasubramaniyam, sorry for any inconvenience, but the screenshot you provided does not show, and the issue you raised is not present in the PR. You focused more on describing Docker and all.

- However, this time I'll merge this PR only for you, but try to make it more attractive. Thank you!

**Review by mdazfar2 — APPROVED** [review]

**Comment by DharshiBalasubramaniyam** [comment]
> Okay @DharshiBalasubramaniyam, sorry for any inconvenience, but the screenshot you provided does not show, and the issue you raised is not present in the PR. You focused more on describing Docker and all.
> 
> * However, this time I'll merge this PR only for you, but try to make it more attractive. Thank you!

Images are visible in the readme in your repo. I have discussed about github actions in the 4th section

**Pull request merged**
