### PR TITLE
Added OTP and Profile pages UI

### LINKED ISSUE #682: Feat: Add UI for OTP verification and Forgot Password
### Describe the feature

Currently our website doesn't have a email verification method while creation of a new user, also we lack a forgot password featuree... I would like to design UI for these 2 components

### Add ScreenShots

Glimpses of UI:

Otp
Profile

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
## Description

Fixes #682 

- Added UI for `OTP` and `Profile`
- Added validators for both the pages

## Video

For `OTP`:

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/e8591d15-73b0-4bf6-b313-332115588a92

For `Profile`:

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/38a7159a-d718-4668-856f-17b524533fce

### CODE REVIEW

**Comment by Asymtode712** [comment]
@mdazfar2 Please review and merge this PR

**Comment by mdazfar2** [comment]
@Asymtode712, I think there is no need for it because this page is for creating a new account after email verification. If the email is not verified, then how will the user set everything from here? It also takes up space.

<br>

image

**Comment by Asymtode712** [comment]
@mdazfar2 Ok....fixing this now

**Comment by mdazfar2** [comment]
@Asymtode712, after clicking on continue on the OTP page, it should open the username and password page. Also, add a small black arrow here so the user can go back to change the email.

<br>

image

**Review by mdazfar2 — APPROVED** [review]
@Asymtode712 Great work

- I am merging it now. There are some changes left, you can do later.

**Comment by Asymtode712** [comment]
@mdazfar2 Done with the changes:

- refactored rendering of `Profile`

  https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/f8fbec5a-26e6-42e0-ae68-deb289001838
  
 - added back button and its functionality in `OTP`:
 
Screenshot (81)

**Comment by Asymtode712** [comment]
@mdazfar2 Done with all the changes which you requested.....please check

**Pull request merged**
