### PR TITLE
added customized Scroll bar

### PR DESCRIPTION
**Pull request by anagha-chaudhari**
Fixes issue #592 

A customized scroll bar is added, if there is any change that needs to be done please let me know

https://github.com/mdazfar2/HelpOps-Hub/assets/143149376/dc2bfd55-3a6c-4823-b37f-8403f32fe810

### CODE REVIEW

**Comment by mdazfar2** [comment]
@anagha-chaudhari the color is not matching with the background correct it! Thanks

**Comment by anagha-chaudhari** [comment]
Okay

**Comment by anagha-chaudhari** [comment]
@mdazfar2 Sir do you like any color out of these?

scroll1
scroll2
scroll3

**Comment by mdazfar2** [comment]
@anagha-chaudhari first one of these three

**Comment by anagha-chaudhari** [comment]
Okay

**Comment by anagha-chaudhari** [comment]
@mdazfar2 I've changed the color to the one you mentioned. Please check

**Comment by anagha-chaudhari** [comment]
I have synced the fork now. can you please review @mdazfar2

**Pull request closed without merging**
