### PR TITLE
Added Chatbox

### PR DESCRIPTION
**Pull request by sidhigrover**
Screenshot 2024-06-07 at 12 26 08 PM

### CODE REVIEW

**Comment by sidhigrover** [comment]
@mdazfar2 sir,please check how this chatbox is looking.

my pull request have 4 failing checks.
please help me their.

**Comment by mdazfar2** [comment]
> @mdazfar2 sir,please check how this chatbox is looking.
> 
> my pull request have 4 failing checks. please help me their.

@sidhigrover 
- Update the sync fork
- use `git pull` on your local machine
- and changes according to your requirement
- and then `git push` 
- come to github
- create pull request

  - If still there is problem then let me know

**Comment by mdazfar2** [comment]
By the way @sidhigrover we are creating a new website on it so could you please add this feature on our website?

<br>

image

<br>

This is the figma design so according to this could you please help me out with your feature?

**Review by mdazfar2 — CHANGES_REQUESTED** [review]
@sidhigrover There is no option to close the chatbox 

- & also don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by sidhigrover** [comment]
> @sidhigrover There is no option to close the chatbox
> 
> * & also don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
> * And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

oh yes. give me some time I will add closing button too

**Comment by mdazfar2** [comment]
> > @sidhigrover There is no option to close the chatbox
> > 
> > * & also don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
> > * And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
> 
> oh yes. give me some time I will add closing button too

Take ur time

**Comment by sidhigrover** [comment]
> @sidhigrover There is no option to close the chatbox
> 
> * & also don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
> * And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

i m unable to join your Discord server

**Comment by sidhigrover** [comment]
> > @mdazfar2 sir,please check how this chatbox is looking.
> > my pull request have 4 failing checks. please help me their.
> 
> @sidhigrover
> 
> * Update the sync fork
> * use `git pull` on your local machine
> * and changes according to your requirement
> * and then `git push`
> * come to github
> * create pull request
>   
>   * If still there is problem then let me know

I never used git Bash before. i always use github desktop for it .

**Pull request closed without merging**
