### PR TITLE
Text set to black in light mode

### PR DESCRIPTION
**Pull request by zalabhavy**
issue #985 

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Please check it and merge !

Thank You !

**Review by mdazfar2 — APPROVED** [review]
Thank you @zalabhavy

**Comment by mdazfar2** [comment]
@zalabhavy can you add here a button `comment` where after clicking on comment it will send comment successfully for all the blog posts which will come in future.

<br>

image

**Comment by zalabhavy** [comment]
@mdazfar2 Yes I will do it !
I will create an issue

**Pull request merged**
