### PR TITLE
Hover of sponser button in team page and overlap of menu items 

### LINKED ISSUE #498: BUG: contact and meet our team overlapping and hovering effect is not working on sponser in team page .
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

contact and meet our teem overlapping and hovering effect on sponser  is not working on sponser page .
Screenshot 2024-06-19 004915

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/dd51b440-1b1d-4db6-ba53-5229d5f181ba

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #498 

fixed hovering effect of sponser button in team page . 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/02ec60fe-fc71-45e9-b210-6fd06db4abb1

fixed overlapping of menu icon with meet our team 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9148ac88-a3f3-440a-8024-9ca371ff4f9e

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 please review it once and merge my pull request under gssoc label .

**Review by mdazfar2 — APPROVED** [review]
@ANKeshri Your pull requests and descriptions are very clear. Thank you for your work in making HelpOps-Hub a success. :)

**Comment by ANKeshri** [comment]
@mdazfar2 my pleasure .

**Comment by mdazfar2** [comment]
@ANKeshri please don't forget to follow us on [linkedin](https://linkedin.com/company/HelpOps-Hub/).

**Comment by mdazfar2** [comment]
Hi @ANKeshri, as you can see, there are many things on our landing page that don't look attractive. I will give you the Figma design for the landing page. Could you please try to make it the same as the Figma design?

- Here is the [Figma](https://www.figma.com/design/eqORN85KL4gsh5qxqNMVFx/Helpops-hub?node-id=0-1&t=R7VNx1nxOtRou001-0). Just look at the landing page design. You need to make it exactly like the Figma design. You have to work on only landing page. Hope you understand what I mean. 

- Raise an issue if you want to work on it.

**Comment by ANKeshri** [comment]
> Hi @ANKeshri, as you can see, there are many things on our landing page that don't look attractive. I will give you the Figma design for the landing page. Could you please try to make it the same as the Figma design?
> 
> * Here is the [Figma](https://www.figma.com/design/eqORN85KL4gsh5qxqNMVFx/Helpops-hub?node-id=0-1&t=R7VNx1nxOtRou001-0). Just look at the landing page design. You need to make it exactly like the Figma design. You have to work on only landing page. Hope you understand what I mean.
> * Raise an issue if you want to work on it.

I am working on it

**Pull request merged**
