### PR TITLE
fix text not visible in dark mode

### LINKED ISSUE #521: Feat: wanted to add hovering effect to DevOps Arsenal icons
### Describe the feature

according to the theme of project there must be hovering effect on the icons  of DevOps Arsenal and fix the night mode on Expert DevOps Insights .
image
image

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/b9d7fe3b-690d-4797-8e28-f6e31dc64088

wanted to hover like this .

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixed #521 
 fixed the text which was not visible in dark mode .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/1e6eb784-e902-41f4-943d-8132681959eb

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 please review once and merge my pull request

**Review by mdazfar2 — APPROVED** [review]
@ANKeshri looks good to me ✨

**Comment by ANKeshri** [comment]
> @ANKeshri looks good to me ✨

thanks @mdazfar2 


https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/d536196c-7c02-4c7c-9a3f-27ec3b7de8bf

-  few second age I found this as a bug if you want me to solve it then only i will create issue and solve it tomorrow . 

- If you want to add any other features do let me know I will be very happy to work on it . 

- thanks

**Comment by mdazfar2** [comment]
@ANKeshri raise issue

**Comment by mdazfar2** [comment]
Hey @ANKeshri, can you fix this alignment as shown in the screenshot below? If you want to work on it, please raise an issue and create a PR. We need it.

<br>

image

**Comment by ANKeshri** [comment]
> Hey @ANKeshri, can you fix this alignment as shown in the screenshot below? If you want to work on it, please raise an issue and create a PR. We need it.
> 
> 
> image

sure @mdazfar2

**Comment by mdazfar2** [comment]
Raise issue with screenshot which i shared you and then creare PR asap @ANKeshri

**Pull request merged**
