### PR TITLE
Feat:Convert Profile Page UI from CSS to Tailwind CSS #876

### PR DESCRIPTION
**Pull request by nishant0708**
Make profile ui using Tailwind and fixed Modal Darkmode bugs as well #876

### CODE REVIEW

**Comment by mdazfar2** [comment]
@nishant0708 resolve your conflict and update your sync fork

**Comment by nishant0708** [comment]
hey @mdazfar2 check it now

**Comment by mdazfar2** [comment]
hey @nishant0708 I noticed that you removed {{username}} and {{password}} and replaced them with your name. Please change it as soon as possible. This type of change cannot fetch the user's details.

<br>

image

**Comment by nishant0708** [comment]
okay wait a sec

**Comment by nishant0708** [comment]
hey @mdazfar2 Sorry for the trouble check it now

**Comment by nishant0708** [comment]
Hey @mdazfar2 please check it whenever possible

**Comment by mdazfar2** [comment]
@nishant0708, now it looks fine. Please update the sync fork and let me know.

**Comment by nishant0708** [comment]
hey @mdazfar2 please check it now

**Review by mdazfar2 — APPROVED** [review]
Looks good to me ✨

**Pull request merged**
