### PR TITLE
About Style fix and Video Added

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #266

I added 3d effects on images.
I made About page's image Styled with adding effect like Shadow , hover and transitions.
Align all sentence in one align as shown in screenshot.
Added a youtube official video.

https://www.loom.com/share/a6d599c6dbba424dbd8ddebbf0a7c7cd

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Please  check i create new PR after sync and this is updated PR.

**Comment by zalabhavy** [comment]
@mdazfar2 please check it i want to make another issue and work on that for this repo !!

**Review by mdazfar2 — APPROVED** [review]
Thank you @zalabhavy

**Comment by mdazfar2** [comment]
Hi @zalabhavy could you make like this in our landing page?


https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/4e86c701-714e-426c-b647-e1095a576e34

- the source code is available [here](https://github.com/XceeDesigns/Website).
- raise an issue for this.

**Pull request merged**
