### PR TITLE
enhanced about page

### PR DESCRIPTION
**Pull request by ayush-848**
For issue #1062

https://www.awesomescreenshot.com/video/29636805?key=0c71faa06bc327521b3ecf6df824f9fa

### CODE REVIEW

**Comment by ayush-848** [comment]
@mdazfar2 please check this

**Comment by mdazfar2** [comment]
Hey @ayush-848 That's awesome, I like it.

- There is text on top of the video that is overlapping, so please remove that text. I think it will look more awesome after removing it.

- The background of the footer is not matching the upper section, so please compare it with the footer on other pages to understand the difference.

- Please update comments so other developers can understand your code update.

**Comment by ayush-848** [comment]
> Hey @ayush-848 That's awesome, I like it.
> 
> * There is text on top of the video that is overlapping, so please remove that text. I think it will look more awesome after removing it.
> * The background of the footer is not matching the upper section, so please compare it with the footer on other pages to understand the difference.
> * Please update comments so other developers can understand your code update.
image
do you mean this as overlapping

**Comment by mdazfar2** [comment]
Nope

**Comment by ayush-848** [comment]
> Nope

Then which one??. I didn't understood

**Comment by mdazfar2** [comment]
<br>

Look at the above@ayush-848

**Comment by ayush-848** [comment]
> 
> 
> 
> Look at the above which was highlight by red color square @ayush-848

Oh got it.
Should I remove it??
Or can you suggest me something

**Comment by mdazfar2** [comment]
I think Removing it would be better

**Comment by mdazfar2** [comment]
@ayush-848 and please also update this part write from your side according to the website.

<br>

image

**Comment by ayush-848** [comment]
@mdazfar2 i have removed the overlapping, replaced the lorem ipsum and commented my code

**Comment by mdazfar2** [comment]
@ayush-848 the footer bg is not matching to the above bg please compare to the other page footer.

<br>

image

**Comment by ayush-848** [comment]
> @ayush-848 the footer bg is not matching to the above bg please compare to the other page footer.
> 
> 
> image

oh yeah, forgot about that

**Comment by ayush-848** [comment]
@mdazfar2 the footer color is ok, but the page color is not matching ig

**Comment by mdazfar2** [comment]
> @mdazfar2 the footer color is ok, but the page color is not matching ig

Yes @ayush-848

**Comment by ayush-848** [comment]
@mdazfar2 now check.

**Review by mdazfar2 — APPROVED** [review]
Thank you @ayush-848

**Comment by mdazfar2** [comment]
> @mdazfar2 do you have any other frontend works??

Sure, if there is any frontend work, I will definitely mention you.

**Comment by ayush-848** [comment]
> > @mdazfar2 do you have any other frontend works??
> 
> Sure, if there is any frontend work, I will definitely mention you.

Sure thanks

**Comment by mdazfar2** [comment]
Hey @ayush-848 🙋‍♂️

Can you change something in our homepage frontend? Wait, I will share which section I am talking about changing in the homepage.

<br>

image

<br>

- **checkout the below demo video which i want same after scroll down.** 👇

<br>


https://github.com/user-attachments/assets/6e058b85-0a37-4ea0-b0ae-5051425c61f3

<br>

> I am waiting for your reply! Thank you

**Comment by ayush-848** [comment]
> Hey @ayush-848 🙋‍♂️
> 
> Can you change something in our homepage frontend? Wait, I will share which section I am talking about changing in the homepage.
> 
> 
> image
> 
> 
> * **checkout the below demo video which i want same after scroll down.** 👇
> 
> 
>  after.scroll.down.mp4 
> 
> > I am waiting for your reply! Thank you

You mean to add interactive elements

**Comment by ayush-848** [comment]
@mdazfar2 I can give it a try
So I should change bthe part between navbar and footer?

**Comment by mdazfar2** [comment]
> @mdazfar2 I can give it a try So I should change bthe part between navbar and footer?

yes, It has to be implemented at the place where it is

**Pull request merged**
