### PR TITLE
Fixed  Mode is not working properly in resources page

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have fixed the mode changing in resources page on reloading it is acting as usual .

closes : #606 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/31faac8a-3a57-4b2d-83df-443977f912cb

### CODE REVIEW

**Comment by shreyash3087** [comment]
sorry to interrupt here but @Ayushmaanagarwal1211 can you tell how to replicate this issue on the website,i cant replicate this bug

**Comment by Ayushmaanagarwal1211** [comment]
@shreyash3087 bro click on get started and then reload the page you will able to see this

**Comment by mdazfar2** [comment]
> sorry to interrupt here but @Ayushmaanagarwal1211 can you tell how to replicate this issue on the website,i cant replicate this bug,for me its working fine

@shreyash3087 I also see that bug. Please check it once from your side as Ayushmaan said and let me know. I am waiting to merge this PR.

**Comment by Ayushmaanagarwal1211** [comment]
Bro may be this is due to the version wait

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/7bb6a22e-363e-4ace-9d96-3a57e95f0d0a

**Comment by Ayushmaanagarwal1211** [comment]
Uploading bandicam 2024-06-24 16-48-11-579.mp4…

**Comment by Ayushmaanagarwal1211** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/97737691-d427-4a6d-8d7b-60d426894c81

**Comment by shreyash3087** [comment]
@mdazfar2 if you can replicate the bug so there might be this bug on some devices,for me its working all fine,although you can merge the pr,if it fixes the issue.

**Comment by mdazfar2** [comment]
@shreyash3087 from my side 

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/869d8946-1243-446e-ae02-014322bae6b6

**Comment by Ayushmaanagarwal1211** [comment]
> @shreyash3087 from my side
> 
>  2024-06-24.14-38-36.mp4

Hmm same same issue on my side as well

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  Please try this i am not sure about version but i did some changes it should work accordingly

**Review by mdazfar2 — APPROVED** [review]
lgtm

**Pull request merged**
