### PR TITLE
Contact Us placeholder color fixed in dark mode

### PR DESCRIPTION
**Pull request by alpharsh**
before:
Screenshot 2024-06-20 224541

after:
Screenshot 2024-06-21 225412

closes: #542

### CODE REVIEW

**Comment by mdazfar2** [comment]
@alpharsh you just changed the color of text @alpharsh

**Comment by alpharsh** [comment]
@mdazfar2 please review and merge this PR and for any changes please feel free to contact

**Comment by alpharsh** [comment]
yes for the darktheme

**Comment by alpharsh** [comment]
by mis

**Comment by mdazfar2** [comment]
@alpharsh will merge after some time

**Pull request closed without merging**
