### PR TITLE
README fetch 2.0

### PR DESCRIPTION
**Pull request by Apurv7777**
## Added to Website 2.0.
Revert / Continuation of  #308

### CODE REVIEW

**Comment by Apurv7777** [comment]
Please review it . @mdazfar2

**Comment by mdazfar2** [comment]
@Apurv7777 screenshot is not visible-

<br>

image

**Comment by Apurv7777** [comment]
It was alignment problem in that README file . I suggest you to ask contributors to fix the alignment itself. @mdazfar2

**Comment by mdazfar2** [comment]
@Apurv7777 What type of alignment are you referring to in the GitHub Readme.md? Every screenshot looks good in the Readme.md file on GitHub, so why is it not shown on the website after fetching? You are also a contributor, so please try to fix it yourself.

**Comment by Apurv7777** [comment]
- @mdazfar2 Fetching is not in my hand. As you can see, I have corrected the README file, and now the screenshots are properly visible. Have you seen the changes done in README file ?  As a PA , first you have to see the changes.

- Correct indentation is very much important in the README files.

**Comment by mdazfar2** [comment]
@Apurv7777 I looked but still screenshots are not visible

**Comment by Apurv7777** [comment]
> @Apurv7777 I looked but still screenshots are not visible

It is only due to some styling error.

- Some errors , Github fetches it correctly and shows the screenshot (problem like indentation) .

**Comment by Apurv7777** [comment]
image

As in the above picture, due to some more indentation , the screenshot is not visible.

**Comment by Apurv7777** [comment]
> @Apurv7777 but in README.md it is visible is that any condition that it is visible

No it is not. Earlier , I am also not believing it . But, changing these small changes, it works. No these only, there are several other takecares for README file , to get fetched properly. @mdazfar2

**Comment by mdazfar2** [comment]
@Apurv7777 will let you know about that

**Comment by mdazfar2** [comment]
@Apurv7777 Can you apply a few effects like hover effect at navbar and some buttons also? If you want to work on it, raise an issue and create pr I'll assigning you

**Comment by Apurv7777** [comment]
> @Apurv7777 will let you know about that

What's the update ?

**Comment by Apurv7777** [comment]
Not updating still, worst experience @mdazfar2 @sanjay-kv

**Comment by mdazfar2** [comment]
- @Apurv7777 The changes that i want to get done, you are not able to do that change. 
- @sanjay-kv Sir these people send pr so that they can get points, these people never think about how we can make their project best.
<br>
<br>

image
<br>
- See the same guy create issue again and again so that's why they are getting points, instead of this he can also create one issue attaching of these issues.

**Comment by Apurv7777** [comment]
@mdazfar2 @sanjay-kv , I have created individual issues because they are for new project proposal. It must be individual. So , you can assigned whichever you think should be added and best for your website. I am not **thirsty** for this PR points. I first learned and contribute. In this repo, I learned how to fetch files, creating hovering effect , etc. while contributing. But @mdazfar2, you are not valuing it and just keep asking other things to do. I just chosen the wrong project to work on.

**Comment by Apurv7777** [comment]
> - @Apurv7777 The changes that i want to get done, you are not able to do that change. 
> - @sanjay-kv Sir these people send pr so that they can get points, these people never think about how we can make their project best.
> <br>
> <br>
> 
> image
> <br>
> - See the same guy create issue again and again so that's why they are getting points, instead of this he can also create one issue attaching of these issues.

Don't you know , the points are issued for PR , not issues. @mdazfar2

**Comment by mdazfar2** [comment]
@Apurv7777 I don't know why you are reacting like this. I don't have any personal enmity. I talk to every contributor very well, including you. By the way, thank you so much for contributing to our repository. You are also welcome to contribute if you want.

**Pull request closed without merging**
