### PR TITLE
[Bug]: Card Alignment and Overflow

### LINKED ISSUE #211: BUG: Alignment of Team and Contributor Cards
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

The Alignment of Team Card and Contributor Cards is not proper,the cards should be in a proper line,to enhance the UI of the webpage.

**ScreenShots:**

Screenshot (206)

**Additional Context :**

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR fixes the Card Alignment on the contributors page and resolves the card-overflow issue on smaller devices.

**Issue Mentioned:**

Closes #211

**Overflow Bug:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/2ad1f187-e1d4-46d6-aa2a-5f82f4898e57

**Changes made:**

- Removed the Padding from `team-grid`.
- Changed Height to `auto` which was previously causing the error of team card-overflow

**Screenshots:**

Screenshot (210)

**Additional Context:**

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@mdazfar2 along with the alignment i found an overflow issue with the team cards as well so i resolved both,kindly verify,it was just a small bug,nothing major.

**Comment by mdazfar2** [comment]
## @shreyash3087 I told you that you need to move the contributor card and text card here and there. But you have moved the `founder card` and `maintainer card` here and there.

image


## this is what i want please see the highlight line it touches the founder card and maintainer card which means you don't have to move those card but you moved.

image

<br>

- **Hope you understand what i want to say**

**Comment by shreyash3087** [comment]
@mdazfar2 alright i understood,i reverted back the team card as it was and modified the contributor card,can you verify again

**Comment by mdazfar2** [comment]
@shreyash3087 Update the sync fork and update with git pull and then create pull request it is not changing on deployed link

**Comment by shreyash3087** [comment]
@mdazfar2 i synced the fork for both the main as well as fix/team-card-alignment branch,and also did git pull,are the changes still not being reflected on vercel ? in that case what can i do?

**Review by mdazfar2 — APPROVED** [review]

**Pull request merged**
