### PR TITLE
add colouring effect to resources page cards .

### LINKED ISSUE #652: Feat: change the hovering colour in both mode of resources cards
### Describe the feature

in light mode the hover is orange which is not looking good and in dark mode also not looking good .

### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9e3b9d24-b7b9-4453-8c3c-a5417f250ec5

in light mode i will make black and in dark mode orange .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #652 

i have changed the hovering colour of cards in both mode as you can see in the video .

before it was like this : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/da417297-e3b3-4003-a7d2-0a5776df0072

now it is like this 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/9aa591f7-cc1d-4739-92ed-cb4352a9ca0d

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 please review it and merge my pull request under gssoc labels .

**Comment by mdazfar2** [comment]
@ANKeshri update sync fork

**Comment by ANKeshri** [comment]
> @ANKeshri update sync fork

done

**Comment by ANKeshri** [comment]
> > @ANKeshri update sync fork
> 
> done @mdazfar2

**Review by mdazfar2 — APPROVED** [review]

**Pull request merged**
