### PR TITLE
Created Responsive website

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've Created a fully responsive website please check 

closes : #137 

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/53bed0db-6837-46f5-9aaa-197495d76b6c

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
@Ayushmaanagarwal1211 Well, nice, but I saw that the contributor page isn't responsive. Try to resolve this in another issue. This time, I'm merging it only for you.

**Comment by Ayushmaanagarwal1211** [comment]
Ok Sure thanks for merging

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Sir this in this pr i created the responsiveness of whole website except contributors page  as told by mdafzar you can check all my code and i can send you all conversations  page and in other pr i did contruibutors page responsive sir this is not fair with me please do something .

**Comment by sanjay-kv** [comment]
image
image


As mentioned earlier, i appreciate the effort, but as you can see above, its basically multiple PR for addressing same issue, I understand the bugs and you may have to raise multiple PR. 
But as this a competition where leaderboard points are counted. cant give multiple PR labels. 

I initially want to give level3 to this one and remove the other responsive PR levels, I made a mistake, I can correct it by giving level 2

**Comment by Ayushmaanagarwal1211** [comment]
@sanjay-kv  Thank you so much sir for understanding  but #136 is faq's page i wrote whole new html and css with proper designing if possible please revert back it too  otherwise no issues .
And i will keep in mind sir i will not raise these issues again i just raised because 2 weeks ago we were working on old website and last week ago project owner discloses his new website ( Completely Different Website ) so i also did too .

**Comment by sanjay-kv** [comment]
Its okay to raise issue and multiple PR, but giving levels to individual PR is the problem, we understand admin cant keep track on these levels, so that why we came to help them. 

Im trying to understand one thing. Did admin created a new website or modified the themes? 
as you can see below, many complains on this repo, I was bit ruthless when came to review for that. apologies. 

image

**Comment by Ayushmaanagarwal1211** [comment]
> Its okay to raise issue and multiple PR, but giving levels to individual PR is the problem, we understand admin cant keep track on these levels, so that why we came to help them.
> 
> Im trying to understand one thing. Did admin created a new website or modified the themes? as you can see below, many complains on this repo, I was bit ruthless when came to review for that. apologies.
> 
> image

@sanjay-kv  sir actually he created a completely new website as in folder directory you can check website_1 and website 2.0 folders are their this is completely new website if you run index.html in website 1.0 this will route to you on the old website  that's why maybe many peoples are thinking that he is changing his theme just for giving points but that's not true the other website is completely new one and we all are working currently  on only  new website and  trying to make it more attractive with more features website i also have all my previous chats regarding old and new websites . And sir the reason for assigning multiple people is that because many people just raise the issues and doesn't complete it for many days but like me but some peoples including me will complete it within a day like i completed all my tasks within a day  because the website is in starting phase . And sir i am not actually the maintainer of that website he has put my name just because i did too many valuable contributions .

**Comment by sanjay-kv** [comment]
thanks for clarification

**Pull request merged**
