### PR TITLE
Fixed the visibility of buttons on hover

### PR DESCRIPTION
**Pull request by Utsavladia**
#1285

Fixed visibility of buttons on hover to properly visible.

image
image

### CODE REVIEW

**Comment by mdazfar2** [comment]
Hey @Utsavladia, thank you for your PR, but it looks weird compared to the current one, so I have to close these changes. Please don't be discouraged.

**Comment by Utsavladia** [comment]
you can suggest me the design you are expecting for the button and i can make that for this issue ...
@mdazfar2

**Comment by mdazfar2** [comment]
> you can suggest me the design you are expecting for the button and i can make that for this issue ... @mdazfar2

@Utsavladia It already looks very nice which is current once

**Comment by Utsavladia** [comment]
Though not visible clearly you also can see
but ok

**Pull request closed without merging**
