### PR TITLE
thankyou fix

### PR DESCRIPTION
**Pull request by zalabhavy**
issue no #629

image

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@mdazfar2 Please check it now !

**Comment by zalabhavy** [comment]
@mdazfar2 Any changes require ?

**Comment by mdazfar2** [comment]
Hey @zalabhavy sorry for the late response. I was a little busy.
- please update sync fork

**Comment by zalabhavy** [comment]
@mdazfar2 Done please check it !

**Comment by mdazfar2** [comment]
hey @zalabhavy previous changes isn't show in your deployment server I cannot merge this

**Comment by mdazfar2** [comment]
Sure @zalabhavy, I'll tell you the issue if there is one found, and thank you so much for understanding my condition to not merge your PR. :)

**Comment by zalabhavy** [comment]
@mdazfar2 No problem !

**Pull request closed without merging**
