### PR TITLE
Added hover style in Get Start button

### LINKED ISSUE #710: Feat: Make Navbar buttons scale effects like Star us and Get Started it looks good
### Describe the feature

I want in Navbar section when we hover that transformation is left to right not looks good i will add scale effects like star us and get start so when we hover on that it looks some bigger like star us and get start button 

On hover background will same only scale effect i want to change.

### Add ScreenShots

image

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by zalabhavy**
Fixes #710

I have just added hover effects on Get Start button.

Due to addition of arrow minor width of button is increased.

image

### CODE REVIEW

**Comment by mdazfar2** [comment]
@zalabhavy please update sync fork

**Comment by zalabhavy** [comment]
@mdazfar2 In my laptop it is shown Everything is up to date also i have sync a fork !

**Comment by mdazfar2** [comment]
@zalabhavy I just merged a PR 2 minutes ago

**Comment by mdazfar2** [comment]
@zalabhavy I saw that you added extra css file which doesn't make any sense please try to changes some file

**Comment by zalabhavy** [comment]
@mdazfar2 Your last PR merge shown 1 hour ago ! I will check after some time and update it.
image

**Comment by zalabhavy** [comment]
@mdazfar2 Done please check it !

**Pull request closed without merging**
