### PR TITLE
Bug: Fixed Navbar Duplication on All Pages

### LINKED ISSUE #413: BUG:Two Navbar On All Pages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

**Description:**

Dropdown Navbar doesnt disappear if its opened in mobile devices and the size of window is increased while it being opened.

**Steps to Reproduce:**

- Go to Helpops Website:https://www.helpopshub.com/
- Reduce the Screen Width
- Open The Hamburger Menu
- Without Closing the Menu Increase the Screen Width.
- Notice the Navbar Doesnt Disappear

**Video**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/f97b0a23-e336-4720-8ed7-08a3d93115d6

**Additional Context:**

I am happy to contribute by fixing this bug myself. Please let me know if you have any feedback or additional requirements.

[X] I am a GSSOC'24 Contributor

Thank you for considering my request!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR fixes the Navbar Duplication Issue on all pages,earlier when hamburger menu was opened on smaller screen and the screen width was increased without closing the hamburger menu,it was not closing on its own,causing duplication of navbar

**Issue Mentioned:**

Closes #413 

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/13d34d90-3174-4964-bd52-496a90b8bf54

**Additional Context:**

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@mdazfar2 kindly review and merge 

thankyou

**Comment by mdazfar2** [comment]
@shreyash3087 Can you show me the difference between before and after?

**Comment by shreyash3087** [comment]
Yeah one min

**Comment by shreyash3087** [comment]
https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/4afc5227-c05a-4d8c-a7ef-e1cd07d79cd2



Notice How on the main website if i open the hamburger menu and increase the screen width the navbar doesnt close and it creates two navbar,i fixed it as you can see it automatically closes if screen width is increased,so two navbar doesnt appear on the website

**Comment by shreyash3087** [comment]
@mdazfar2 if you have any more queries you can ask

**Review by mdazfar2 — APPROVED** [review]

**Comment by mdazfar2** [comment]
@shreyash3087 Could you add some hover effects on the navbar and some buttons to make them look attractive and impressive according to our website's look? If you think the navbar needs it, please create a PR; otherwise, there might be no need. Please see according to your convenience. If needed, add some nice effects on the navbar and buttons like "Star Us," "Sponsor," and more.

**Comment by shreyash3087** [comment]
@mdazfar2 I can add this animation for the navbar,or if you have any specific effect that you would like me to add,please do tell

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/b2ee0b88-e988-4059-9b78-8f13c9afbd71

**Comment by mdazfar2** [comment]
@shreyash3087 maybe it looks good
- also try to add some effect on some buttons like `sponsor` `star us`

**Comment by shreyash3087** [comment]
@mdazfar2 yeah sure would think something for the sponser and star us button,in the meantime what do you think of this effect for the footer links- 

Screenshot (22)

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/d559e871-828f-4560-85df-15fa71ea2c4d

**Comment by mdazfar2** [comment]
@shreyash3087 it's good but what about sponsor button and star us button

**Comment by shreyash3087** [comment]
@mdazfar2 yes im looking for some good animations,ill inform if i get something good

**Comment by mdazfar2** [comment]
@shreyash3087 indeed

**Comment by mdazfar2** [comment]
did you find anything? @shreyash3087

**Comment by shreyash3087** [comment]
@mdazfar2 Nah nothing looks up to the mark for the sponser button,i think we should leave it for now,ill message you on discord if i get something creative.

**Comment by mdazfar2** [comment]
@shreyash3087 ok Create pr of everything you have analyzed before raising issue.

**Pull request merged**
