### PR TITLE
Added NGINX Reverse Proxy Guide

### LINKED ISSUE #156: Feat: Add NGINX Reverse Proxy Guide to Documentation 📝
### Describe the feature

The documentation currently lacks guidance on configuring NGINX as a reverse proxy server, a critical aspect for improving security and performance in various infrastructures. To address this gap, we propose adding a comprehensive NGINX Reverse Proxy Guide to the documentation.

Feature Details:

The guide will include detailed step-by-step instructions for installing NGINX and configuring it as a reverse proxy.
It will cover prerequisites, installation steps, and configuration of reverse proxy settings, including SSL termination, load balancing, and caching.
Clear explanations, accompanied by code snippets, will be provided to ensure ease of understanding and implementation by users of varying skill levels.
Hands-on tasks will be incorporated to provide users with practical experience in configuring NGINX for various use cases.
This addition aims to enhance the documentation by providing users with a valuable resource for effectively implementing NGINX as a reverse proxy server to optimize their infrastructure's security and performance.

### Add ScreenShots

No response

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
This pull request adds a comprehensive hands-on guide for setting up NGINX Reverse Proxy Guide

fixes #156

### CODE REVIEW

**Comment by thevijayshankersharma** [comment]
@mdazfar2 take a look

**Comment by thevijayshankersharma** [comment]
@mdazfar2 take a look

**Comment by priyanshukumar397** [comment]
kindly check @mdazfar2

**Comment by mdazfar2** [comment]
@thevijayshankersharma @priyanshukumar397 sorry for the late respond!

- But document you have created doesn't make any sense for anyone to learn.

**Comment by thevijayshankersharma** [comment]
@mdazfar2 what should I remove or add in it ? I didn't get your criteria to judge it.

**Comment by priyanshukumar397** [comment]
Which documents? What exactly is not making any sense? Kindly elaborate.

Thanks

**Comment by mdazfar2** [comment]
I have another task for the website. If you guys want to work on it, please let me know, and I'll share it with you. @thevijayshankersharma

**Comment by thevijayshankersharma** [comment]
@mdazfar2 what it is ??

**Comment by mdazfar2** [comment]
@thevijayshankersharma could you add hover effect on all the navbar including `Star Us` `Get Started` button also contributor page;

<br>

image


<br>

- Look at the above screenshot
- After completion of it create pr and I have another issue

**Pull request closed without merging**
