### PR TITLE
add dark mode in resourcesc

### LINKED ISSUE #559: BUG: FIX day and night mode in all the resources
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in the resourse the page is same for the dark and light mode . 

BEFORE : 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/de7dd607-588b-40a6-a885-5da9d23c3a9d

AFTER 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/c5d0eb37-df69-4f43-aa5f-675f4764eba9

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixed #559 

in all the pages of resources dark mode has been added . Here i have shown in few resources but I have made sure that in all the resources page dark mode is working . 

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/cbcf9edf-0afb-4971-a9be-76617d383426

### CODE REVIEW

**Comment by mdazfar2** [comment]
@ANKeshri Can you resolve this one

<br>

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/c8666650-89da-45f2-8942-9e72554e5b3d

<br>

hope you understand what i want

**Comment by ANKeshri** [comment]
> @ANKeshri I don't understand what you changed


https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/a069ab8e-da71-494e-8b8d-4b925e9074bd

earlier video is this in which dark mode is not working . in dark mode also white page was coming .

**Comment by ANKeshri** [comment]
> @ANKeshri Can you resolve this one
> 
> 
>  2024-06-21.18-40-33.mp4 
> 
> hope you understand what i want

these things already fixed

**Comment by ANKeshri** [comment]
> @ANKeshri Can you resolve this one
> 
> 
>  2024-06-21.18-40-33.mp4 
> 
> hope you understand what i want

these things already fixed in this pr only see below .
image

**Comment by ANKeshri** [comment]
@mdazfar2 check it once i have added all the videos of current website and what i have changed

**Comment by mdazfar2** [comment]
@ANKeshri I think you don't understand which bug I am talking about! See, in `Light` mode the bold text is not visible, but in `dark` mode it is visible very well. Try to see the below video.

https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/c8666650-89da-45f2-8942-9e72554e5b3d

**Comment by ANKeshri** [comment]
> > @ANKeshri Can you resolve this one
> > 2024-06-21.18-40-33.mp4
> > hope you understand what i want
> 
> these things already fixed in this pr only see below . image

@mdazfar2 see this I have fixed it

**Comment by mdazfar2** [comment]
@ANKeshri It is not fixed

## In dark mode It is showing all thing good 
image

<br>

## But when i switched to light mode it is not visible as you can see
image

<br>

- Hope you now understand what I am talking about.

**Comment by ANKeshri** [comment]
@mdazfar2 i have fixed that but i dont know why it is not comming so i am closing this pull request and creating new pr .

**Comment by mdazfar2** [comment]
> @mdazfar2 i have fixed that but i dont know why it is not comming so i am closing this pull request and creating new pr .

<br>

Hi @ANKeshri, don't be discouraged if you haven't been able to resolve this issue. You're a great developer, and we all face challenges sometimes. :)

**Comment by ANKeshri** [comment]
> > @mdazfar2 i have fixed that but i dont know why it is not comming so i am closing this pull request and creating new pr .
> 
> 
> Hi @ANKeshri, don't be discouraged if you haven't been able to resolve this issue. You're a great developer, and we all face challenges sometimes. :)

thanks @mdazfar2 for encouraging me . I am doing for the first time . Because of you I am learning a lot new things . Thanks for keeping pacience and making me understand .

**Comment by Asymtode712** [comment]
> @ANKeshri It is not fixed
> 
> ## In dark mode It is showing all thing good
> image
> 
> 
> ## But when i switched to light mode it is not visible as you can see
> image
> 
> 
> * Hope you now understand what I am talking about, and this applies to every topic you can notice, I guess.
> * Let me know if you can resolve this
> 
> Hi @Asymtode712, could you take a look at this and see if you can resolve it?

@mdazfar2 His changes looks fine to me, it should have work with those changes

**Comment by mdazfar2** [comment]
> > @ANKeshri It is not fixed
> > 
> > ## In dark mode It is showing all thing good
> > image
> > 
> > 
> > ## But when i switched to light mode it is not visible as you can see
> > image
> > 
> > 
> > * Hope you now understand what I am talking about, and this applies to every topic you can notice, I guess.
> > * Let me know if you can resolve this
> > 
> > Hi @Asymtode712, could you take a look at this and see if you can resolve it?
> 
> @mdazfar2 His changes looks fine to me, it should have work with those changes

---

@Asymtode712 I think I might need to wait a while on this because, from his side, everything is fine, but on my side, it is not updated.

**Comment by Asymtode712** [comment]
@mdazfar2 No worries.....It would be fine

**Pull request closed without merging**
