### PR TITLE
skeleton added in loading video

### PR DESCRIPTION
**Pull request by Varsani2520**
added skeleton in video loading state in `about page` 

video take some time to fetch then display skeleton otherwise display video

### CODE REVIEW

**Comment by Varsani2520** [comment]
@mdazfar2 ,check it

**Comment by mdazfar2** [comment]
@Varsani2520 I don't see any changes in your PR.

**Comment by Varsani2520** [comment]
@mdazfar2 ,


https://github.com/user-attachments/assets/909d0066-5ebd-4723-9247-cad2d002cfed

**Comment by Varsani2520** [comment]
@mdazfar2 

i added skeleton on about video 
kindly check this and merge it

**Comment by mdazfar2** [comment]
@Varsani2520 update sync fork and let me know!

**Review by Varsani2520 — COMMENTED** [review]
i review it

**Comment by Varsani2520** [comment]
@mdazfar2 ,i update sync fork now check it

**Review by mdazfar2 — APPROVED** [review]
thank you @Varsani2520 for your pr.

Do you remember that you complained about our repository in **GSSoC red flag 🚩** when I didn't give you the **points**? If you don't remember, please check your complaint. I am attaching the link here - [Varsani HelpOps-Hub complaint](https://github.com/GSSoC24/Contributor/discussions/94#discussioncomment-9782987)

- And the same girl created a PR today for **getting points**. I don't know why you girls are like that, but don't worry. **Thank you so much**; you are a good developer and keep contributing. Please don't do things like that again; it hurts me more. 💔

**Comment by Varsani2520** [comment]
ok

**Pull request merged**
