### PR TITLE
Feature to Redirect users to Contribution History Page-Added Hover Effect

### LINKED ISSUE #620: Feat: Open Commit History of User on Clicking the Contributions
### Describe the feature

**Descripiton:**

Clicking on the contributions text of a `user` should open their commit history on helpops website. This feature is essential to show the users contribution history in the Helpops community

### Add ScreenShots

Screenshot (68)

Screenshot (69)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR adds the feature to redirect users to contribution history page of that particular user in the Helpops Repository when the contributions link is clicked on the teams page and Also adds Hover Effect to the links on contributor cards

**Issue Mentioned:**

Closes #620

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/1ff5073e-fe95-44ed-8bf5-92315ff6287c

**Additional Context:**

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@mdazfar2 can you explain a bit what do you want with the first one,`open source contributor` is already written in one line,

for the second one im assuming you want me to increase this margin from bottom,right?

Screenshot (70)

and i understood the third one

**Comment by mdazfar2** [comment]
@shreyash3087 

**1. It is completed on the second one which doesn't look attractive**

<br>

image

<br>

**2. Your assumption is correct**

**3. The text below the link must be underlined which is not underlined right now**

**Comment by shreyash3087** [comment]
@mdazfar2 it should be good now-


https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/e1019e33-739d-4da0-afc7-8f876673f384

**Review by mdazfar2 — APPROVED** [review]
great work @shreyash3087

**Comment by mdazfar2** [comment]
@shreyash3087 I merged it after watching your demo video. but it is not showing here. After clicking on refresh then it will show.

image

**Comment by shreyash3087** [comment]
nextjs is component based,so you dont have to make footer for every page individually,just one footer component is applied to every page automatically,same goes for header also,so if i do change in footer,or header it will be automatically applied to all pages,the underline not appearing till the page is refreshed might be a small bug,ill fix it dont worry

**Pull request merged**
