### PR TITLE
Feedback form

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've added the functionality for email through feedback form .
closes : https://github.com/mdazfar2/HelpOps-Hub/issues/222

Hii if you are going to merge so please give level 3 because you know i also created contact us page whole new page with css but now it becomes of no use .

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  i have created a pr and used my api key and all required information

**Comment by mdazfar2** [comment]
> @mdazfar2 i have created a pr and used my api key and all required information

@Ayushmaanagarwal1211 where are you? How long have i been looking for you?

**Comment by mdazfar2** [comment]
image


@Ayushmaanagarwal1211 showing error?

**Comment by Ayushmaanagarwal1211** [comment]
Because i was in college and giving my external and i just reached my home at 7 pm That's why i become late and someone changes the feedback form code that's why it is happening

**Comment by mdazfar2** [comment]
> Because i was in college and giving my external and i just reached my home at 7 pm That's why i become late and someone changes the feedback form code that's why it is happening

try to do anything but do something

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  actually someone chnaged the code to enter the details in the database so this is the database error due to cors policy error please check console  you can see the error but i got the mail

**Comment by Ayushmaanagarwal1211** [comment]
email : [azfaralam440@gmail.com](mailto:azfaralam440@gmail.com):

message :  I love your website

**Comment by mdazfar2** [comment]
> email : [azfaralam440@gmail.com](mailto:azfaralam440@gmail.com):
> 
> message :  I love your website 

@Ayushmaanagarwal1211 but the user should feel that his mail has been sent successfully.

**Comment by mdazfar2** [comment]
@Ayushmaanagarwal1211 and create an issue for responsive of Homeage and try to make full responsive

**Comment by Ayushmaanagarwal1211** [comment]
So can i remove that database code because this is creating the error because on which url the backend code is hosted that is changes

**Comment by Ayushmaanagarwal1211** [comment]
> @Ayushmaanagarwal1211 and create an issue for responsive of Homeage and try to make full responsive till 9 pm

yes just doing

**Comment by Ayushmaanagarwal1211** [comment]
Please check in my code the api is returning success 

Screenshot 2024-06-06 195901

But after that at the time of database api calling this is raising an error but i can solve it 
Screenshot 2024-06-06 195919

**Comment by mdazfar2** [comment]
> So can i remove that database code because this is creating the error because on which url the backend code is hosted that is changes 

Do whatever you want but nothing should happen to the website. Be careful. @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok for now i am removing the database saving code so it will starting working as usual without error

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  can you please check

**Comment by mdazfar2** [comment]
> Ok for now i am removing the database saving code so it will starting working as usual without error
@Ayushmaanagarwal1211 okk

**Comment by Ayushmaanagarwal1211** [comment]
I think its will solved

**Comment by mdazfar2** [comment]
Listen @Ayushmaanagarwal1211 firstly try to fix responsiveness because it is most important then work on backend feedback

**Comment by Ayushmaanagarwal1211** [comment]
Yes i am start working on responsiveness

**Comment by mdazfar2** [comment]
it is merged now `update sync` and `git pull` and start work on `responsiveness`  @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2    

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/4eee09cb-5c14-4475-aaa3-a0a31864b5e0

i did home page responsive can you please i am attaching the vide below if you didn't like something please tell i will start working on other pages

**Comment by mdazfar2** [comment]
For now home page is enough create or on it!

- i have one more issue for you

@Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
Ok

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  i've just completed and doing faq i have to go for important work but i will sure raise pr before 9:40 pm

**Pull request merged**
