### PR TITLE
Fetching README files

### LINKED ISSUE #308: Feat: Fetching README files to frontend.
### Add ScreenShots

https://github.com/mdazfar2/HelpOps-Hub/assets/65327303/4fa40b36-6a71-4a2c-98fb-b525428e8654

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Apurv7777**
Fixes #308 
- Added functionality of fetching README files.
- Added link to Github Repo , in case , someone wants to visit the Repo. 
- Added functionality to copy the code.

Changes to be fixed by PA :
- Please ask the contributor to create readme file with name ***README.md*** only. Otherwise, it will not fetch successfully.
- Ask contributors to redesign the readme file relative to the website . Means keep looking to website also, that how it is going to appear.  

Please give **level** to this PR accordingly.

Demo :

https://github.com/mdazfar2/HelpOps-Hub/assets/65327303/0079ad36-3196-41bc-b2d5-10639f782d58

### CODE REVIEW

**Comment by mdazfar2** [comment]
@Apurv7777 It is working but screenshot and screen recording doesn't visible in you readme fetching resolve this.

**Comment by Apurv7777** [comment]
> @Apurv7777 It is working but screenshot and screen recording doesn't visible in you readme fetching resolve this.

For which it is not showing ?

**Comment by mdazfar2** [comment]
@Apurv7777 All is well, but the screenshot is not showing, which is available in readme.md. You know that the screenshot is most important to confirm that it is working, so please try to make it again. Our new web is hosted, so please try to add this feature in our new web in our latest folder called [Website2.0](https://github.com/mdazfar2/HelpOps-Hub/tree/main/website2.0).

**Comment by Apurv7777** [comment]
image

Screenshots are visible.

**Comment by mdazfar2** [comment]
> image
> 
> Screenshots are visible.

<br>
<br>

@Apurv7777 yeah now that's amazing

**Comment by Apurv7777** [comment]
I have added to the website 2.0 also . @mdazfar2

**Comment by mdazfar2** [comment]
@Apurv7777 currently we are working on website2.0

**Comment by Apurv7777** [comment]
For now, you can add to website 1.0 also . @mdazfar2

**Comment by mdazfar2** [comment]
> For now, you can add to website 1.0 also . @mdazfar2

<br>

Nope

**Comment by Apurv7777** [comment]
When it is planned to merge ? @mdazfar2

**Comment by mdazfar2** [comment]
@Apurv7777 create or for Website2.0

**Comment by Apurv7777** [comment]
@mdazfar2 created 👍

**Comment by Apurv7777** [comment]
Just delaying , not merging it . @sanjay-kv @mdazfar2

**Pull request closed without merging**
