### PR TITLE
added logo with link and hover effect

### LINKED ISSUE #188: BUG:redirect issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

user click on logo then redirect the home page is missing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Varsani2520**
i added ,when user click on logo then redirect the home page 
as well as add hover effect on the logo 

 BUG:redirect issue #188 
close #188

@mdazfar2 ,check it and merged it

### CODE REVIEW

**Review by mdazfar2 — COMMENTED** [review]
@Varsani2520 It has a bug. Instead of the Vercel link, please try to add index.html on the logo. It will be a problem in the future whenever I add a domain or try to host this with Hostinger or anything else.

**Comment by Varsani2520** [comment]
Hey @mdazfar2 ,
Official_Website/index.html 
this is ok or /index.html

**Comment by Varsani2520** [comment]
ok

**Comment by mdazfar2** [comment]
@Varsani2520 

- & please don't forget to join our official [Discord server](https://discord.gg/UWTrRhqywt) so we can discuss more about HelpOps-Hub enhancement.
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)

**Comment by Varsani2520** [comment]
Hey @mdazfar2 ,i alreay do that

**Comment by Varsani2520** [comment]
when i fork the project then in index.html ,
alreay link is available :`    <a href="https://helpops-hub.vercel.app/"
          >HelpOps-Hub Logo</a>  `   and this is perfect so i can do in all page 

tell me what's the issue that url

only that url redirect the home page 

so we have no option for redirect

**Comment by Varsani2520** [comment]
Hey @mdazfar2 ,
check it and merged it 

i completed as you say
now it doesn't create any problem in add extra domain
please add level label

**Pull request merged**
