### PR TITLE
Added Pre-Loader and Cursor

### LINKED ISSUE #176: Feat: Add A Pre-Loader and a Custom Cursor
### Describe the feature

A Pre-Loader and a custom curosor would make the UI of the website much better as it gives an engaging user experience and uplifts the overall feel of the website.

### Add ScreenShots

**Screenshot-**

screencapture-127-0-0-1-5500-Official-Website-index-html-2024-06-05-09_12_30

**Video-**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/9c7a2c0c-9096-4f57-a44e-d5e45cc6f53e

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

Added Pre-Loader in HomePage and Custom Cursor on all Pages.This Improves the overall User Experience of the Website.

**Changes Made:**

- Added Script.js that contains js for cursor and loader
- modified style.js for styling of cursor and loader
- modified index.html,abouts.html,contributors.html,faq.html to implement custom cursor.

**Issue Mentioned:**

Closes #176 

**Additional Context:**

N/A

### CODE REVIEW

**Review by mdazfar2 — CHANGES_REQUESTED** [review]
@shreyash3087 Please remove the pre-loader effect from the homepage. We require it only for the custom mouse cursor.

- let me know after you remove it.

**Comment by shreyash3087** [comment]
@mdazfar2 Pre-Loader has been removed,you can merge it now

**Review by mdazfar2 — CHANGES_REQUESTED** [review]
@shreyash3087 try to resolve this
<br>

image

- **When the custom-cursor is available, So I think there is no need for bi-default cursor. So remove this bi-default cursor also.**

**Comment by shreyash3087** [comment]
@mdazfar2 Alright,Removed the Default Cursor,Kindly Review

**Review by mdazfar2 — CHANGES_REQUESTED** [review]
@shreyash3087 I saw again bi-default cursor is not removed. And I think your custom-cursor is a bit delay in case of Bi-default.

- could you resolve it?

**Comment by shreyash3087** [comment]
@mdazfar2 Can you check again,I removed the Default cursor,changed every cursor styling to be `cursor:none` ,it should not appear on most of the page,you might still be able to see the cursor appear if you hover your some links like `FAQ` or social media icons like Github etc, if those are removed user wont know if those icons can be clicked or not.So I think those are good at their place

Also the cursor has a lazy animation that triggers on mouse movement,that makes it look like its delayed,if you have any more changes,you can tell me.

**Comment by shreyash3087** [comment]
@mdazfar2 can you merge it, if there is no issue now

**Pull request closed without merging**
