### PR TITLE
Changed position of form and image

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I have changed the position of form and image to slightly right side keeping in mind about responsiveness  .

https://github.com/mdazfar2/HelpOps-Hub/assets/118350936/8d9ea72e-e07d-40a9-9cee-b3509cd2066b

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  i have to go clg tomorrow so i am raising this pr if any conflict occur or you didn't like something let me know i will do it today morning Good Night !

**Comment by mdazfar2** [comment]
> @mdazfar2 i have to go clg tomorrow so i am raising this pr if any conflict occur or you didn't like something let me know i will do it today morning Good Night !

in which time you wake i'll also come online on that time @Ayushmaanagarwal1211

**Comment by Ayushmaanagarwal1211** [comment]
I woke up but reach my clg at 9 am so i can work after 9 am

**Comment by Ayushmaanagarwal1211** [comment]
@mdazfar2  i am online

**Comment by mdazfar2** [comment]
> @mdazfar2 i am online

@Ayushmaanagarwal1211 vercel deployment is failed now

**Comment by Ayushmaanagarwal1211** [comment]
Ok please wait 30 min I am giving my external exam I will raise pr before 11 am

**Comment by Ayushmaanagarwal1211** [comment]
I am creating another pr

**Pull request closed without merging**
