### PR TITLE
Feat: Converted Classes to BEM Naming Convention

### LINKED ISSUE #604: Feat: Convert Classnames on All Pages to follow BEM naming Convention
### Describe the feature

To improve the maintainability, scalability, and readability of our CSS, we need to refactor the class names across all pages of the website to follow the BEM (Block, Element, Modifier) naming convention. The BEM methodology helps create reusable and modular code, making it easier to manage and less prone to conflicts.

**Tasks:**

- Review Current Class Names
- Refactor Class Names
- Update Stylesheets
- Update JavaScript

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR converts classes to follow BEM naming convention,and fixes a margin issue on the Resources Page.

**Issue Mentioned:**

Closes #604

**Changes Done-**

- Converted ClassNames on `HomePage.jsx`,`AboutsPage.jsx`,`ContactPage.jsx`,`ResourcesPage.jsx`,`ResourcesDetailsPage.jsx` to BEM Naming Convention.
- Converted ClassNames on `homepage.css`,`abouts.css`,`contact.css`,`resources.css`,`resourceloader.css`,`resourcedetails.css`
- Deleted `website2.0` directory

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/d2676bce-3ab8-42d5-92bc-51758e727500

**Additional Context:**

This PR is half of the full convertion work,the next half will be done in next PR

### CODE REVIEW

**Comment by shreyash3087** [comment]
@mdazfar2 Someone had changed the margin of resources page by mistake i think so i fixed that as well-

Screenshot (71)

Screenshot (72)

**Comment by shreyash3087** [comment]
@mdazfar2 also before merging this PR kindly preview it on vercel first,and see if there's any issue,because it might be possible i might have missed any class by mistake(im a human)

**Comment by mdazfar2** [comment]
> @mdazfar2 Someone had changed the margin of resources page by mistake i think so i fixed that as well-
> 
> Screenshot (71)
> 
> Screenshot (72)
> 

Already raised issue for that @shreyash3087

**Comment by shreyash3087** [comment]
@mdazfar2 no problem then thats good

**Comment by mdazfar2** [comment]
update sync fork @shreyash3087

**Comment by shreyash3087** [comment]
@mdazfar2 already did,its showing up to date

**Comment by mdazfar2** [comment]
It is not showing up to date you can compare with the current ones: @shreyash3087 

<br>

image

**Comment by shreyash3087** [comment]
@mdazfar2 just the contact page is not updated right? ill fix it,any other page which is not updated??

**Comment by mdazfar2** [comment]
@shreyash3087 you already solved this right?

<br>

image

**Comment by shreyash3087** [comment]
@mdazfar2 the margin issue? yes i did

**Comment by mdazfar2** [comment]
> @mdazfar2 just the contact page is not updated right? ill fix it,any other page which is not updated??
> 

You solved for resource bugs right?? If it is solved please mention issue #641 as solved

**Comment by shreyash3087** [comment]
alright will mention that and update the contactus page,just give me a minute

**Comment by mdazfar2** [comment]
@shreyash3087 check out the dark mode in `about` page there is color issue in text as well as `team`

**Comment by shreyash3087** [comment]
alright

**Comment by mdazfar2** [comment]
@shreyash3087 look at this also

<br>

image

**Comment by mdazfar2** [comment]
@shreyash3087 There are many bugs in dark mode when we reload in team and contact. I think I should not merge this. Can we close this one? I think there is no need for BEM convention. please don't feel bad :)

**Comment by shreyash3087** [comment]
@mdazfar2 thats totally fine =) i wont have to do more work then on other pages,you can close it i think,its just that the codebase has become so large even i dont know which element is having effects form which classes sometimes they have effect from other page classes.
I think you should close it.

**Pull request closed without merging**
