### PR TITLE
Fixed resources header and added Sort & Filter

### LINKED ISSUE #641: Feat: Fixing the Resources header and adding Sort & Filter
### Describe the feature

Currently, the header of Resources page of our site has components overlapping each other, also it lacks a Sort & Filter option for sorting the contents in a proper order.

### Add ScreenShots

Nav

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
## Description

Fixes #641 

- Added `Sort` and `Filter` feature for the `Resources` page for sorting and filtering the available Docs
- Adjusted `Sort` and `Filter` according to the Dark Theme
- Updated `handleSearch` function to be compatible with the Sort & Filter featured
- Fixed the header in `Resources` page

## Video

https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/5d838341-5a38-46ac-b375-a2eb8863cbdd

## Screenshots

r1
r2

### CODE REVIEW

**Comment by Asymtode712** [comment]
@mdazfar2 Please review and merge this PR

**Comment by mdazfar2** [comment]
@Asymtode712 fix this navbar as well when we open any specific topics-

<br>

image

**Comment by Asymtode712** [comment]
@mdazfar2 Sure just a sec

**Comment by Asymtode712** [comment]
@mdazfar2 Done!

**Comment by mdazfar2** [comment]
@Asymtode712, do one more thing: change this to the top and write it this way so the user can understand the use of this icon. According to your convenience, try to add and write from your side.

<br>

image

**Comment by Asymtode712** [comment]
@mdazfar2 Ok as you wish!!

**Comment by Asymtode712** [comment]
@mdazfar2 Is this looking fine to you:



https://github.com/mdazfar2/HelpOps-Hub/assets/115717746/b4cd5c0a-13e4-450a-907b-f0037767986e

**Comment by mdazfar2** [comment]
@Asymtode712 nice update it and also add hover on the icon of `more info`

**Comment by Asymtode712** [comment]
@mdazfar2 Done!

**Review by mdazfar2 — APPROVED** [review]
Thank you @Asymtode712

**Pull request merged**
