### PR TITLE
Fixed Height and Width of  boxes in mobile view #394

### PR DESCRIPTION
**Pull request by dhairyagothi**
Fixed height and width of boxes please merge the PR and add GSSOC label 
solving issue #394 

Thanku for opportunity @mdazfar2

### CODE REVIEW

**Comment by mdazfar2** [comment]
@dhairyagothi share demo video as well

**Comment by dhairyagothi** [comment]
After :

https://github.com/mdazfar2/HelpOps-Hub/assets/142989448/869f67c6-6f34-4f51-9119-acdee6ab512a

before :
image

**Comment by mdazfar2** [comment]
@dhairyagothi ig you forget to add hamburger

**Comment by dhairyagothi** [comment]
> @dhairyagothi ig you forget to add hamburger

What is hamburger can you please explain 
i have just changed CSS in mobile view nothing else

**Comment by mdazfar2** [comment]
@dhairyagothi this is called hamburger in responsive

<br>

image

**Comment by dhairyagothi** [comment]
> @dhairyagothi this is called hamburger in responsive
> 
> 
> image

okay i will add that but initially this is not in resources page
i will add this and make a PR asap

**Comment by mdazfar2** [comment]
> > @dhairyagothi this is called hamburger in responsive
> > image
> 
> okay i will add that but initially this is not in resources page i will add this and make a PR asap

<br>

@dhairyagothi for sure

**Comment by dhairyagothi** [comment]
image
Added @mdazfar2

**Comment by mdazfar2** [comment]
@dhairyagothi Update you sync fork.

**Comment by dhairyagothi** [comment]
> @dhairyagothi Update your sync fork.

Done 👍🏻

**Comment by mdazfar2** [comment]
Thank you @dhairyagothi 

- join our official [Discord server](https://discord.gg/UWTrRhqywt).
- And also follow us on [Linkedin](https://linkedin.com/company/HelpOps-Hub/)
- And please ⭐ our repo

**Pull request merged**
