### PR TITLE
Feat/password visibility

### LINKED ISSUE #684: FEAT: hide and view password functionality
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

in light mode filter button is not visible and also orange hovering is not visible in light mode want to add black hovering as you can see in the video .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/2f0626de-417f-4a75-a3a3-0220feca7089

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by ANKeshri**
fixes #684 
added view and hide password functionality .

https://github.com/mdazfar2/HelpOps-Hub/assets/159682348/e44a0e1b-11f6-4d23-8843-b70070ebcb5b

### CODE REVIEW

**Comment by ANKeshri** [comment]
@mdazfar2 since i am currently in process of learning js therefore I am countered so many hinderance therefore it took me some extra time to complete that  but finally i have added . please preview it and merge

**Comment by mdazfar2** [comment]
@ANKeshri adjust this 

<br>

image

**Comment by mdazfar2** [comment]
@ANKeshri you have not added any comments again please add

**Comment by ANKeshri** [comment]
@mdazfar2 done
+-

**Comment by ANKeshri** [comment]
> @ANKeshri If you enter your email when creating a new account, you should receive an email in your Gmail, but this isn't happening on your deployment server. Please compare with the deployment web. Could you close this PR and issue for now please because someone is working on it? If something goes wrong, there will be significant authentication problems. Hope you understand :) Thanks!

@mdazfar2 I have just added a feature in which user can see password while entering and nothing else you can close if not wanted .

**Comment by mdazfar2** [comment]
@ANKeshri 
Can you add some effects to some buttons? I can share a demo video if you want.

**Comment by ANKeshri** [comment]
> @ANKeshri Can you add some effects to some buttons? I can share a demo video if you want.

@mdazfar2 please share it

**Comment by mdazfar2** [comment]
@ANKeshri here in the following below for hover effect please let me know

<br>


https://github.com/mdazfar2/HelpOps-Hub/assets/100375390/92e3e963-63d1-465d-b194-6556e5c4e276

**Pull request closed without merging**
