### PR TITLE
added backend to contributors page

### PR DESCRIPTION
**Pull request by pandeyji711**
@mdazfar2 
### please mark Gssoc24 Level 3
Screenshot 2024-06-03 115507

### CODE REVIEW

**Review by mdazfar2 — APPROVED** [review]
Great work @pandeyji711

**Comment by Yashgabani845** [comment]
@mdazfar2 @pandeyji711 is it allowed to make PR without raising issue?
beause you are doing it

**Comment by sanjay-kv** [comment]
I will be removing the repo from the program , if you are not ready to follow guidelines. 
I have mentioned to you earlier as well. 

Dont assign level3, even if you assign leaderboard is transparent to everyone, contributor are gonna flag to us. 
+ I noticed you been merging the PR''s of this person without creating issues. 
Can I know whats really happening here?

**Comment by pandeyji711** [comment]
@sanjay-kv I have added backent to the website that is 178 lines of code!!!

**Comment by pandeyji711** [comment]
@sanjay-kv  for rising issue i will take care of it next time!!

**Comment by rajnishdesai23** [comment]
@pandeyji711 bro check your other level3 PRs 
just adding button 
adding social icons
Adding dark theme

**Comment by pandeyji711** [comment]
### Adding dark theam
 we have to takel  js , we have to select element manage colour , managing transitions , 
its not just colour change!!!!
please cheak the darkmode pr , and resultent feature

**Comment by sanjay-kv** [comment]
@mdazfar2 I will put your repo on hold until manual review finish as I see recent few PR's when I check into the Code changes its doesn't qualify for the same. which is creating lot of issue among other contributors trusting this program leaderboard. 

I have requested access to repo to manage as well.

**Comment by pandeyji711** [comment]
@sanjay-kv
###   This Pr is capable for level 3 I have added Backend 178 lines of code ande manage  apis

**Comment by pandeyji711** [comment]
@sanjay-kv I am agree that
 adding button 
adding social icons   is not meens for level 3
 ### But in all other I have worked A lot!!!

**Comment by mdazfar2** [comment]
@sanjay-kv please accept my request and manage accordingly 

- have you got it?

**Comment by rajnishdesai23** [comment]
@pandeyji711 
don't worry he will not remove all 
edit thoses which are needed to be

**Comment by pandeyji711** [comment]
@Yashgabani845 Thank you for your understanding. I will ensure to arrising issue  first in the future.

**Comment by sanjay-kv** [comment]
Hi i got the invite .

Thanks for adding me, i will be making some changes in labels. 

https://github.com/mdazfar2/HelpOps-Hub/pull/72/files especially like this one. 

Dont think like I'm taking too much authority over here, but to run program smoothly this action has to be taken, I wont be putting your project on hold.  but I hope you would be okay with changing some of the labels in your repo. 


you can give level3 if you need but if one person getting level3 for these changes for multiple PRs is making the issue in the community and counted as spamming. 

I hope you understand the seriousness of this issue. I have seen your repo, its really good, keep adding additional features but be very careful on assigning level 3 labels as it has 45 points.

**Comment by sanjay-kv** [comment]
> @Yashgabani845 Thank you for your understanding. I will ensure to arrising issue first in the future.

Im not demotivating you as well, I saw your contribution looking at your code base. its amazing, not everyone is capable of doing such things. but its just the label issues in general. keep doing great contribution. sorry about any inconvenience caused to you @pandeyji711

**Pull request merged**
