### PR TITLE
Feat: Integrated Contact Us Form to MongoDB Database

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR integrates the Contact Us form to the existing MongoDB Database,which ensures the proper functioning of Contact Us Form

**Issue Mentioned:**

#678 

**Changes Done:**

- Integrated Contact Us form to MongoDB Database

**Video:**

https://github.com/mdazfar2/HelpOps-Hub/assets/72603662/bcacaddf-0487-4d75-87a8-a10da5e5d4a4

**Additional Context:**

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@mdazfar2 kindly review

**Comment by mdazfar2** [comment]
@shreyash3087 Received fake email also in my DB

**Comment by shreyash3087** [comment]
yes that will be fixed when i find an alternative of hunter

**Review by mdazfar2 — APPROVED** [review]
Nice it's working

**Pull request merged**
