### PR TITLE
Add Carousel Testimonial Section to Homepage

### LINKED ISSUE #1445: [Feat] Add User Testimonial Carousel Section at Home Page
### Description

**Description**  
To enhance the HelpOps Hub homepage experience, we need to add a "User Testimonial Carousel" section. This section will display user testimonials in a visually appealing carousel format, allowing visitors to quickly see feedback from satisfied users. This addition aims to build trust and increase user engagement on the platform.

**Feature Requirements**  
1. **Carousel Component**  
   - Create a responsive carousel to showcase user testimonials.
   - Each slide should display a testimonial, including the user’s name, profile picture, and feedback text.
   
2. **Testimonials Content**  
   - Add sample testimonials for testing. Each testimonial should include:
      - User’s name
      - Profile picture
      - Short feedback (limited to 200 characters)
      - Rating

3. **Responsive Design**  
   - Ensure the carousel looks good on all screen sizes (desktop, tablet, and mobile).

4. **Animation and Transitions**  
   - Smooth transitions between testimonials.
   - Autoplay functionality with the option to pause on hover (for desktop view) or tap (for mobile view).

### Screenshots

https://github.com/user-attachments/assets/aed7833f-8aad-4907-99a7-28c73af57c44

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [ ] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by IkkiOcean**
## Description
This pull request introduces a carousel testimonial section on the homepage to enhance user engagement and showcase community feedback. The carousel allows users to view multiple testimonials easily, improving the overall user experience.

## Features Implemented
- Added a responsive carousel component that displays user testimonials.
- Implemented automatic transitioning between testimonials every few seconds.
- Included navigation buttons for manual control over the testimonial display.
- Ensured compatibility across different screen sizes with responsive design adjustments.

## Related Issues

- Closes #1445 

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/19b65c0e-5574-4426-a718-239262596495

### CODE REVIEW

**Comment by mdazfar2** [comment]
@IkkiOcean It must be the alignment with the newsletter's section alignment

<br>

{FEDF5DBE-CC64-44C4-87CC-8708103B66E8}

<br>

And try to make it a bit smaller; it currently takes up the full screen, which doesn’t look professional or attractive. Adjust it to appear more professional.

image

**Comment by IkkiOcean** [comment]
> @IkkiOcean It must be the alignment with the newsletter's section alignment
> 
> 
> {FEDF5DBE-CC64-44C4-87CC-8708103B66E8}
> 
> 
> And try to make it a bit smaller; it currently takes up the full screen, which doesn’t look professional or attractive. Adjust it to appear more professional.
> 
> image

okay 👍

**Comment by IkkiOcean** [comment]
@mdazfar2 check now!

Screenshot 2024-11-06 at 10 11 56 AM

**Review by mdazfar2 — APPROVED** [review]
amazing work

**Comment by IkkiOcean** [comment]
@mdazfar2 do let me know if you have any other feature in mind for ezyshop!

**Pull request merged**
