### PR TITLE
light and dark mode completed

### PR DESCRIPTION
**Pull request by Varsani2520**
i complete dark and light theme ,
@mdazfar2 ,check it and merge it

### CODE REVIEW

**Comment by Varsani2520** [comment]
@mdazfar2 ,also add the label as per #353

**Comment by mdazfar2** [comment]
@Varsani2520 You change only the gradient which doesn't make any sense.

- Suppose someone visits my website for learning purposes and has an eye problem, so they start the dark mode. However, the dark mode doesn't work properly because you have only changed the color.
- You had correctly applied dark mode in the previous website.

**Comment by Varsani2520** [comment]
Ok i will do it

**Comment by Varsani2520** [comment]
In dark mode which type of background you wont 

Gradient type or simply black as per previous website  choose one

**Comment by mdazfar2** [comment]
@Varsani2520 Do you really don't know which type of color are use in dark mode?

**Comment by Varsani2520** [comment]
Dark theme based on admin choice 
Not a specific color 
Usually use a black color but I was try to your web look unique and good if you don't like then i remove it and apply dark color it you want

**Comment by RamakrushnaBiswal** [comment]
hi @Varsani2520 btw its not the correct way to add darkmode in the website
you make changes in 1000 lines of code add it...

**Comment by mdazfar2** [comment]
@Varsani2520 I have another idea to share with you. We want to add something new, and I want to pass this idea over to you. If you’re interested, I can share it with you.

**Comment by Varsani2520** [comment]
Ok tell me

**Comment by RamakrushnaBiswal** [comment]
@mdazfar2 can you assign it to me i can implement Darkmode effectively

**Comment by mdazfar2** [comment]
> Ok tell me

<br>

@Varsani2520 I have announced it right now in [Discord](https://discord.com/channels/1247249565682237683/1247255340756504716/1250922662666965032), please check it out and let me know.

**Comment by mdazfar2** [comment]
Hey @Varsani2520, you did not reply yet about our new idea. Then you will say that I don't give you any level, give l level only to Pandeyji.

**Comment by Varsani2520** [comment]
@mdazfar2 

you removed me from assign
than why i should give  reply 

actually i completed almost work and in between you removed me from assign
this is not fair 
if you not want to give me than tell me

**Comment by mdazfar2** [comment]
> @mdazfar2
> 
> you removed me from assign than why i should give reply
> 
> actually i completed almost work and in between you removed me from assign this is not fair if you not want to give me than tell me

<br>

Actually i was not have noticed. I may have mistakenly unassigned you @Varsani2520 
- By the way, what do you think about our new idea? Leave working on the dark theme. I will give you level 3 on another issue, don't worry.
- As you must know, I am a man of my word :)

**Pull request closed without merging**
