### PR TITLE
Added chatbox 

### PR DESCRIPTION
**Pull request by sidhigrover**
Screenshot 2024-06-07 at 12 26 08 PM

### CODE REVIEW

**Comment by mdazfar2** [comment]
> @mdazfar2 Screenshot 2024-06-07 at 3 36 36 PM
> 
> I made the new pull request, after updating the sync fork. same issue is coming

ignore this @sidhigrover

**Comment by mdazfar2** [comment]
@sidhigrover still you were no added any close button on chat bot

**Comment by sidhigrover** [comment]
> @sidhigrover still you were no added any close button on chat bot

I will add it .give me some time

**Comment by sidhigrover** [comment]
> @sidhigrover still you were no added any close button on chat bot

you wanted this chatbox in your other website too?

**Comment by mdazfar2** [comment]
> > @sidhigrover still you were no added any close button on chat bot
> 
> you wanted this chatbox in your other website too?

<br>

yes we are working on it

**Comment by sidhigrover** [comment]
@mdazfar2 
sir,check now i fixed the issue

**Comment by sidhigrover** [comment]
> > > @sidhigrover still you were no added any close button on chat bot
> > 
> > 
> > you wanted this chatbox in your other website too?
> 
> 
> yes we are working on it

can i can work on your  other project too?

**Comment by mdazfar2** [comment]
@sidhigrover Let you know about new project

**Comment by sidhigrover** [comment]
> @sidhigrover Let you know about new project

please you can merge my pull request

**Comment by sidhigrover** [comment]
> @mdazfar2 sir,check now i fixed the issue

please you can merge my pull request

**Comment by sidhigrover** [comment]
> @sidhigrover Let you know about new project



> @mdazfar2 sir,check now i fixed the issue

Sir,I fixed the issue ,if you don't need any further changes, please you can merge my pull request.

**Comment by mdazfar2** [comment]
@sidhigrover great work but please update sync fork and then create pull req because you are not updated in main branch

**Comment by sidhigrover** [comment]
> @sidhigrover great work but please update sync fork and then create pull req because you are not updated in main branch
@mdazfar2 
I updated sync fork .

**Comment by mdazfar2** [comment]
@sidhigrover try again becausein my production doesn't shown recent deployment which i was merged

**Pull request closed without merging**
